### ISSUE TITLE
Add version number of service name

### ISSUE THREAD

**Issue by sdunnagan** [engelmi/hirte#100]
I read about the importance of the version number in a D-Bus API:
https://dbus.freedesktop.org/doc/dbus-api-design.html

An example is org.freedesktop.login1.  Maybe should add a '1' to org.containers.hirte.

**Comment by alexlarsson** [comment]
I actually don't agree with that rule, as it makes the names harder to read, and not having a foo, like foo1 does in no way limit the ability to create a foo2 name. But, conventions here vary from project to project, we just need to decide on one.

**Comment by sdunnagan** [comment]
Closing this as not an issue.
