### ISSUE TITLE
Add integration tests for bluechi-is-online agent with --wait parameter

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#1000]
## Please describe what you would like to see

In https://github.com/eclipse-bluechi/bluechi/issues/962 the new package bluechi-is-online was introduced. However, adding integration tests was postponed. 

A basic integration test for `bluechi-is-online agent` would verify that:
- It exits immediately with code 0 when the `bluechi-agent` is connected
- If bluechi-agent is not connected upon bluechi-is-online execution, bluechi-is-online waits with specified timeout and return 0 if bluechi-agent get connected within this timeout
- If bluechi-agent is not connected upon bluechi-is-online execution, bluechi-is-online waits with specified timeout and return non-zero if bluechi-agent doesn't get connected within this timeout

<br>
<br>

**Tech hints**
- To properly test `--wait` parameter you will need to run `bluechi-is-online agent` in separate thread, for inspiration about using threads in integration tests you can take a look at https://github.com/eclipse-bluechi/bluechi/blob/main/tests/tests/tier0/bluechi-request-cancel/test_bluechi_request_cancel.py

**Comment by DanaOrr** [comment]
Please assign to me
