### ISSUE TITLE
Add integration tests for bluechi-is-online system without any cli options

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#1001]
## Please describe what you would like to see

In https://github.com/eclipse-bluechi/bluechi/issues/962 the new package bluechi-is-online was introduced. However, adding integration tests was postponed. 

A basic integration test for `bluechi-is-online system` would verify that:
- It exits with code 0 when all registered `bluechi-agent` instances are connected
- It exists with code 1 when at least one of registered `bluechi-agent` is not connected

<br>
<br>

**Tech hints**
- `bluechi-is-online system` needs to run on the controller node

**Comment by nsimsolo** [comment]
Please assign to me
