### ISSUE TITLE
e2e Tests as part of github workflow

### ISSUE THREAD

**Issue by Yarboa** [engelmi/hirte#119]
## Add tests to cover various hirte dbus scenarios

As part of review resolve issue #118 the following idea came up
https://github.com/containers/hirte/pull/104#issuecomment-1419296579

## Testing linrary and framework
Python package https://github.com/rhinstaller/dasbus
Could be integrated easily inside pytest fremwork

## hirte scenarios
test_registered_node_proxy()
/org/containers/hirte/node/foo
test_offline_node_proxy()
/org/containers/hirte/node/bar
test_not_exist_node_proxy()
/org/containers/hirte/node/fye

**Comment by mwperina** [comment]
Shouldn't we use [tmt](https://tmt.readthedocs.io/en/stable/overview.html)? I've heard that this is the framework that QE use in other teams ...

**Comment by Yarboa** [comment]
Good point, We will use tmt, once hirte github action will run on TestingFarm runner

**Comment by Yarboa** [comment]
Closing this,  test strategy for e2e will change soon
