### ISSUE TITLE
Use generated hirte rpms inside e2e wokflow

### ISSUE THREAD

**Issue by Yarboa** [engelmi/hirte#158]
## Hirte e2e images should use rpmbuild workflow outputs

Based on the following discussion
https://github.com/containers/hirte/pull/152#pullrequestreview-1305672866

##  rpm-artifacts of the workflow should be copied into the hirte-image

Remove this part: https://github.com/containers/hirte/blob/main/.github/workflows/e2e.yaml#L26-L32
And copy the generated rpms into container and dnf local install

**Comment by engelmi** [comment]
I think we can use the [upload/download artifact feature](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) of github. We already upload the RPM artifact from the build (see [here](https://github.com/containers/hirte/blob/main/.github/workflows/build.yml#L100-L104)). This can be downloaded and installed in the hirte test container. For an example, see the [download artifact github action](https://github.com/actions/download-artifact#download-a-single-artifact).

**Comment by Yarboa** [comment]
Thanks,

**Comment by ygalblum** [comment]
But if this is done as port of the CI, we have to make sure that the E2E test is executed after the artifacts for the PR and built and that the test uses the correct version (the same one of the PR)

**Comment by Yarboa** [comment]
> But if this is done as port of the CI, we have to make sure that the E2E test is executed after the artifacts for the PR and built and that the test uses the correct version (the same one of the PR)

Correct
Need to find the best way out of the follwoing to consume the rpms 
1) Call https://github.com/containers/hirte/blob/main/.github/workflows/build.yml#L57
2) move rpmbuild job into e2e workflow

**Comment by engelmi** [comment]
Not sure if there are any pitfalls, but maybe the [trigger workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) can set that dependency. For example, in our case on the `Build` it would look like this:
```yaml
// e2e.yaml
name: E2E
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed
```
