### ISSUE TITLE
metrics: implement metrics infra + life-cycle operation roundtrip measurements

### ISSUE THREAD

**Issue by mkemel** [engelmi/hirte#160]
We need to provide metrics in hirte.
1. Prepare infra for reporting metrics. Proposal: dbus signals. This way this can (not necessarily) be done by a separate service.
2. First metrics - separate time measurement on life-cycle operations (start/stop/restart/reload) - how much time it took to hirte itself and how much time it took to systemd.

**Comment by alexlarsson** [comment]
Also, this should be something that can be disabled on the live system, as we don't want to do unnecessary work when not used.

**Comment by engelmi** [comment]
Done in #265. Closing.
