### ISSUE TITLE
Research D-Bus permissions

### ISSUE THREAD

**Issue by sdunnagan** [engelmi/hirte#164]
This issue is to research D-Bus permissions, and how to prevent unauthorized users from sending
messages on a bus.  The long term goal is to run Hirte on the system bus, and the system bus by
default is limited for any user except root.  There is an XML file for opening up access rights, and
that's how you can control who can do what.

**Comment by rhatdan** [comment]
Just to add further info here.  SELinux would also control which processes are allowed to communicate with the dbus, and can allow certain SELinux labels to communicate with certain services running under DBUS.  Not sure we will ever handle this in RHIVOS.  Bottom line, even containers running as Root will be blocked by default from communicating with dbus.
