### ISSUE TITLE
The content of configuration files

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#172]
## The Location of hirte configuration files

Location of hirte configuration files is described in https://github.com/containers/hirte/issues/147 and https://github.com/containers/hirte/issues/148

## The content of hirte configuration files

Configuration files for hirte are using [systemd configuration file](https://www.freedesktop.org/software/systemd/man/systemd.syntax.html) format.

#### The default configuration file
Here is the example of the hirte manager configuration file, which contains all valid options at the time of writing this issue:

```
# This is the default configuration file for the hirte manager.
#
# All available options are describe in hirte.conf man page or in
# hirte-default.conf file provided by hirte package.
#

[hirte]
# The level used for logging. Supported values are: DEBUG, INFO, WARN and ERROR.
LogLevel=INFO

#
# The target where logs are written to. Supported values are: journald and
# stderr.
LogTarget=journald

#
# If this flag is set to true, no logs are written by hirte.
LogIsQuiet=false

#
# The port the manager listens on to establish connections with the hirte
# agents.
ManagerPort=2020

#
# A comma separated list of unique hirte-agent names. These are used as
# a whitelist to validate any register request from each hirte-agent.
AllowedNodeNames=
```

#### Standard configuration file

There is `/etc/hirte/hirte.conf` file installed as a part of hirte RPM packages with following content:

```
# This is the configuration file for hirte manager.
#
# All available options are describe in hirte-agent.conf man page or in
# hirte-default.conf file provided by hirte-agent package.
#
[hirte]
```

#### Customize hirte manager configuration

There are different ways how to customize configuration if the hirte manager. For example if a user would like to enable debug logging, there are 2 ways to do it:

1. Edit existing file `/etc/hirte/hirte.conf` and add a line containing `LogLevel=DEBUG`:

   ```
   # This is the configuration file for hirte manager.
   #
   # All available options are describe in hirte-agent.conf man page or in
   # hirte-default.conf file provided by hirte-agent package.
   # 
   [hirte]
   LogLevel=DEBUG
   ```

2. Create a new file (for example `99-debug-logging.conf`) inside `/etc/hirte/hirte.conf.d/` with following content:

   ```
   [hirte]
   LogLevel=DEBUG
   ```

#### The default configuration file
Here is the example of the hirte agent configuration file, which contains all valid options at the time of writing this issue:

```
# This is the default configuration file for the hirte agent.
#
# All available options are describe in hirte-agent.conf man page or in
# hirte-default.conf file provided by hirte-agent package.
#

[hirte]
# The level used for logging. Supported values are: DEBUG, INFO, WARN and ERROR.
LogLevel=INFO

#
# The target where logs are written to. Supported values are: journald and
# stderr.
LogTarget=journald

#
# If this flag is set to true, no logs are written by hirte.
LogIsQuiet=false

#
# The unique name of this agent.
# It's mandatory to set this option for each hirte-agent.
NodeName=

#
# The host used by hirte-agent to connect to hirte manager. It must be a valid
# FQDN, IPv4 or IPv6 address.
# It's mandatory to set this option for each hirte-agent.
ManagerHost=

#
# The port the manager listens on to establish connections with the hirte
# agents.
ManagerPort=2020
```

#### Standard configuration file

There is `/etc/hirte/agent.conf` file installed as a part of hirte-agent RPM packages with following content:

```
# This is the configuration file for hirte agent.
#
# All available options are describe in hirte-agent.conf man page or in
# hirte-default.conf file provided by hirte-agent package.
#
[hirte-agent]
# The unique name of this agent.
# It's mandatory to set this option for each hirte-agent.
NodeName=

#
# The host used by hirte-agent to connect to hirte manager. It must be a valid
# FQDN, IPv4 or IPv6 address.
# It's mandatory to set this option for each hirte-agent.
ManagerHost=
```

#### Customize hirte agent configuration

There are different ways how to customize configuration if the hirte agent. For example if a user would like to enable debug logging, there are 2 ways to do it:

1. Edit existing file `/etc/hirte/agent.conf` and add a line containing `LogLevel=DEBUG`:

   ```
   # This is the configuration file for hirte manager.
   #
   # All available options are describe in hirte-agent.conf man page or in
   # hirte-default.conf file provided by hirte-agent package.
   # 
   [hirte-agent]
   LogLevel=DEBUG
   ```

2. Create a new file (for example `99-debug-logging.conf`) inside `/etc/hirte/agent.conf.d/` with following content:

   ```
   [hirte-agent]
   LogLevel=DEBUG
   ```

**Comment by pypingou** [comment]
This looks good to me

**Comment by rhatdan** [comment]
All fields possible should have defaults, and the system configuration file should list the defaults.

```
# This is the default configuration file for the hirte manager.
#
# All available options are describe in hirte.conf man page or in
# hirte-default.conf file provided by hirte package.
#

[hirte]
# The level used for logging. Supported values are: DEBUG, INFO, WARN and ERROR.
# LogLevel=INFO

#
# The target where logs are written to. Supported values are: journald and
# stderr.
# LogTarget=journald

#
# If this flag is set to true, no logs are written by hirte.
# LogIsQuiet=false

#
# The port the manager listens on to establish connections with the hirte
# agents.
# ManagerPort=2020

#
# A comma separated list of unique hirte-agent names. These are used as
# a whitelist to validate any register request from each hirte-agent.
# AllowedNodeNames=
```

**Comment by mwperina** [comment]
> All fields possible should have defaults, and the system configuration file should list the defaults.
> 
> ```
> # This is the default configuration file for the hirte manager.
> #
> # All available options are describe in hirte.conf man page or in
> # hirte-default.conf file provided by hirte package.
> #
> 
> [hirte]
> # The level used for logging. Supported values are: DEBUG, INFO, WARN and ERROR.
> # LogLevel=INFO
> 
> #
> # The target where logs are written to. Supported values are: journald and
> # stderr.
> # LogTarget=journald
> 
> #
> # If this flag is set to true, no logs are written by hirte.
> # LogIsQuiet=false
> 
> #
> # The port the manager listens on to establish connections with the hirte
> # agents.
> # ManagerPort=2020
> 
> #
> # A comma separated list of unique hirte-agent names. These are used as
> # a whitelist to validate any register request from each hirte-agent.
> # AllowedNodeNames=
> ```

Do we need to have defaults hard coded in source code? Isn't it better to load defaults from `/usr/share/hirte/config/hirte-default.conf`? Such file shouldn't be edited by user and RPM will raise an issue when this is edited.

Of course the customizable file `/etc/hirte/hirte.conf` can be edited by users, that's what this file is meant for.

**Comment by rhatdan** [comment]
I prefer software to work without configuration files, and this also allows you to update/change the configuration in the furture without forcing users to change their config.
Imagine you choose log-level=debug as the default prior to release and then you switch to warn. Now all users have to change their config.

If hirt becomes popular and is used on multiple distributions, the config files will change and get out of date.

If you want to add more values in the future, you will force users to change their config.

**Comment by mwperina** [comment]
> I prefer software to work without configuration files, and this also allows you to update/change the configuration in the furture without forcing users to change their config. Imagine you choose log-level=debug as the default prior to release and then you switch to warn. Now all users have to change their config.
> 
> If hirt becomes popular and is used on multiple distributions, the config files will change and get out of date.
> 
> If you want to add more values in the future, you will force users to change their config.

But those changes will happen in `/usr/share/hirte/config/hirte-default.conf`, which is a file totally under our controll (it's always overwritten during package upgrade). While user customization will happen either in `/etc/hirte/hirte.conf` (which is marked as configuration file in RPM, so we will not overwrite user's customization during package upgrade) or in `/etc/hirte/hirte.conf.d/<NN>-<CUSTOM FILE>.conf` which we fully manager by users and we don't touch during package upgrade.

So I think that above approach allows us to perform any changes in the default configuration without too much hassle to users (of course except the case if we decide to rename or remove some option).

**Comment by rhatdan** [comment]
Normal user action I have seen in this is to 
cp /usr/share/hirte/config/hirte-default.conf /etc/hirte/hirte.conf

Then user edits /etc/hirte/hirte.conf and makes their change, this cements the defaults for the user.
If later versions of hirte come out with changed defaults, this user will not get those changes.

This makes changing the defaults in general much harder.
If the  /usr/share/hirte/config/hirte-default.conf file lists the defaults but commented out, because they are in code,
then the problem of copying the file and uncommenting only the line the user wants to modify resolves the issue.

**Comment by mwperina** [comment]
That's true, but the plan is a bit different:

* `/usr/share/hirte/config/hirte-default.conf` will contain all options to set defaults values
* `/etc/hirte/hirte.conf` will be created during RPM installation, but it will contains only mandatory options without default. So for hirte it will contain only comments:
```
# This is the configuration file for hirte manager.
#
# All available options are describe in hirte-agent.conf man page or in
# hirte-default.conf file provided by hirte-agent package.
#
[hirte]
```
but for example for `hirte-agent.conf` it will contain below:
```
# This is the configuration file for hirte agent.
#
# All available options are describe in hirte-agent.conf man page or in
# hirte-default.conf file provided by hirte-agent package.
#
[hirte-agent]
#
# The unique name of this agent.
# It's mandatory to set this option for each hirte-agent.
NodeName=

#
# The host used by hirte-agent to connect to hirte manager. It must be a valid
# FQDN, IPv4 or IPv6 address.
# It's mandatory to set this option for each hirte-agent.
ManagerHost=
```
Sorry, only now I figured out that I will need to fix the description I provided about :-(
