### ISSUE TITLE
Allow more dynamic permissions

### ISSUE THREAD

**Issue by alexlarsson** [engelmi/hirte#187]
Currently permissions to access the hirte manager API is controlled by the dbus-daemon policy configuration files. For example, `/usr/share/dbus-1/system.d/org.freedesktop.systemd1.conf` specifies who can contact systemd and what APIs they can use. However, these permissions are quite static (to update you write a xml file and send a signal to dbus-daemon).

The ability to allow permissions to be slightly more dynamic has been requested. For example, a service that uses hirte to manage the system would have full permissions, but it may want to somehow assign permission to a subset of the systems to another service. Given examples are: 
 * ability to pre-create a monitor and let another service consume it, 
 * ability to have a specific job visible and trackable by another service

Actually changing how permissions are handled will be hard, but we can perhaps ensure that the existing permission system can be used for this. For example, it may be useful to be able to give a predefined name to a monitor (in addition to the current id), such that a static permission can be used to grant access to it.

This needs more research.

**Comment by alexlarsson** [comment]
One particular request here has been the ability to hand over monitor events from a pre-created monitor to a peer other than the one that created it. I think this could be done by adding a new monitor api AddPeer(string peer_name)  which will then just make hirte send monitor events to that peer (as well as the creator). 

This means we don't need any specific permission changes to allow this.

**Comment by alexlarsson** [comment]
Actually we seem to be broadcasting monitor events today rather than sending them to the monitor creator only, so anyone can see the events. Maybe we should change this too.

**Comment by engelmi** [comment]
> Actually we seem to be broadcasting monitor events today rather than sending them to the monitor creator only, so anyone can see the events. Maybe we should change this too.

Yes, we were broadcasting 3 of the 4 monitor signals. This has been fixed in #642 - now a BlueChi Monitor only sends it to the peer that created it. 

> One particular request here has been the ability to hand over monitor events from a pre-created monitor to a peer other than the one that created it. I think this could be done by adding a new monitor api AddPeer(string peer_name) which will then just make hirte send monitor events to that peer (as well as the creator).
> 
> This means we don't need any specific permission changes to allow this.

I think if we implement the `AddPeer` API for monitoring, then this will be sufficient for this issue. Signals about Job state changes are broadcasted (and I think should be), so nothing to do for it. 

Therefore, these are the TODOs:
- [x] implement AddPeer API
- [x] integration test(s)
- [x] update documentation

**Comment by engelmi** [comment]
Implementation, tests and documentation done. Closing.
