### ISSUE TITLE
Set LogLevel via D-Bus API

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#189]
## Please describe what you would like to see

~~While `hirte` and/or `hirte-agent` are running, the should be a mechanism to trigger a reload. This reload should case the services to reload the configuration.~~

Edit: see [comment below](https://github.com/containers/hirte/issues/189#issuecomment-1560632309)

## Please describe the solution you'd like

- ~~`hirte` and `hirte-agent` should expose a public API for reloading~~
- ~~The service files need to be extended to call this API on `ExecReload`~~

~~This is based on [ExecReload in systemd.service man page](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecReload=):~~
> Note however that reloading a daemon by enqueuing a signal (as with the example line above) is usually not a good choice, because this is an asynchronous operation and hence not suitable when ordering reloads of multiple services against each other. It is thus strongly recommended to either use Type=notify-reload in place of ExecReload=, or to set ExecReload= to a command that not only triggers a configuration reload of the daemon, but also synchronously waits for it to complete. For example, [dbus-broker(1)](https://www.mankier.com/1/dbus-broker) uses the following:
>       ExecReload=busctl call org.freedesktop.DBus 
>              /org/freedesktop/DBus org.freedesktop.DBus 
 >             ReloadConfig

**Comment by ArtiomDivak** [comment]
Some suggestions to clarify what needs to be done in the reload API.
I will describe how I see the reload please feel free to say your opinion.

1. First, what parameters of the configuration parameters should support the reload?
   * (my suggestion supported: LogLevel, LogTarget,  LogIsQuiet not supported: Port, AllowedNodeNames).
2. Let's say the port is supported by the reload and the user changed the port of the manager.
Should the agent be notified and even reload with the new port?
3. Now Let's say the Port is not supported by the reload should we fail the reload and send an error that says 
you need to call restart to change the port.

If there is any other functionality that you think needs to be added, please write them.

**Comment by engelmi** [comment]
Good questions @ArtiomDivak 

I think as a first step for the reload it is sufficient to support only fields that don't affect any connections, e.g. the port and host for agents as well as the port and allowed node names for the manager. At least for now. I don't know how hirte will be used here and this would be important to know choosing an approach. 
Taking your example of the changed port for the manager: This would affect the manager and all connected agents. Therefore, I'd assume a flow like this:
- config files on all nodes incl. the manager are updated
- a reload is executed on the manager 
- detecting the change in port, the manager notifies the agents to reload as well
- manager drops all connections (or waits till all agents are disconnected) and starts listening on a new port 
- agents try to connect on new port

But how do we handle if some agents don't connect again, e.g. config hasn't been updated? "Rollback" somehow? I don't know. Because it seems rather complex, I'd only implement a reload for config options unrelated to connection for now. What do you think? @alexlarsson @mkemel  @sdunnagan

**Comment by mwperina** [comment]
I think the reload operation should take action only for a service which is executed for (ie. reloading hirte shouldn't cause any action on hirte-agent instances). The reload operation should really be used only for non-disrupting options like changing log level. If an admin wants to change something significant (for example port or address), then it should be done by stopping the agents, then hirte, perform this disrupting change and then starting again.

Let's not overcomplicate things ...

**Comment by ArtiomDivak** [comment]
First, we need to understand the difference between restart and reload functionality.
Because changing the port is supposed to be part of restart. So I support Martin's suggestion that reload should take action only on non-disturbing options

**Comment by engelmi** [comment]
After discussion, we decided to drop the Reload feature entirely. Instead, we introduce a public D-Bus API for changing the log level. The D-Bus API needs to be extended like this:
- SetLogLevel(in s) -> on the `manager_vtable` for setting level on hirte
- SetLogLevel(in s) -> on the `node_vtable` for setting level on the node which calls the SetLogLevel on `internal_agent_vtable`
- SetLogLevel(in s) -> on the `internal_agent_vtable` for setting level on agent

So setting the log level happens only via the public D-Bus API of the local (system) bus where hirte is running on and can be triggered via hirtectl, for example. 

## Acceptance Criteria:

- The methods listed above are implemented
- Documentation is updated
   - in the api description: https://github.com/containers/hirte/blob/main/data/org.containers.hirte.Agent.xml#L5
   - in the data directory: https://github.com/containers/hirte/tree/main/data
- Optional: extend hirtectl by a new command to set the log level
   - `hirtectl set-node-loglevel [node] [level]` : set log level for given agent. if [node] is not given, it fans out to **all** nodes
   - `hirtectl set-loglevel [level]` : set log level for hirte
   - documentation (usage function and man pages) has to be updated as well

**Comment by engelmi** [comment]
Done in #347. Closing.
