### ISSUE TITLE
Add e2e test scenario for proxy

### ISSUE THREAD

**Issue by Yarboa** [engelmi/hirte#221]
## e2e testing for proxy scenario

Service A on node bar, dependent on service B on node foo

Send with hirtectl command to start service A on node bar
Service B on node foo, is down, once service B is up,
Service A status is up and running

**Comment by engelmi** [comment]
The following description shows a few test cases that should be covered: 

## Basic setup

agent foo --> manager <-- agent bar

## Basic Units

```INI
# complex-sleep.service
[Unit]
Wants=hirte-proxy@bar_simple-sleep.service
After=hirte-proxy@bar_simple-sleep.service

[Service]
ExecStart=/usr/bin/sleep infinity
```

```INI
# simple-sleep.service
[Unit]
Description=Just sleeping

[Service]
Type=simple
ExecStart=/usr/bin/sleep infinity
```

## Test Cases

The state of units should be verified using `hirtectl list-units` to query (and filter) units and check their status. 

### (A) Starting a proxy service :heavy_check_mark:  (https://github.com/containers/hirte/pull/290)

_Steps:_

1. Using `hirtectl`, start `complex-sleep.service` on `agent foo`
2. Verify state

_Expected Result:_

| agent | service | state |
|---|---|---|
| foo | compolex-sleep.service | active |
| foo | hirte-proxy@bar_compolex-sleep.service | active |
| bar | simple-sleep.service | active |
| bar | hirte-dep@simple-sleep.service | active |

    
### (B) Stopping a proxy service on the source node :heavy_check_mark: (https://github.com/containers/hirte/pull/297)

_Prerequisites:_ 

- Steps from (A)

_Steps:_

1. Using `hirtectl`, stop `complex-sleep.service` on `agent foo`
2. Verify state 

_Expected Result:_

| agent | service | state |
|---|---|---|
| foo | compolex-sleep.service | inactive |
| foo | hirte-proxy@bar_compolex-sleep.service | inactive |
| bar | simple-sleep.service | inactive |
| bar | hirte-dep@simple-sleep.service | inactive |


### (C) Stopping the actual (dependency) service on the target node

_Prerequisites:_ 

- Steps from (A)

_Steps:_

1. Using `hirtectl`, stop `simple-sleep.service` on `agent bar`
2. Verify state 

_Expected Result:_

| agent | service | state |
|---|---|---|
| foo | compolex-sleep.service | inactive |
| foo | hirte-proxy@bar_compolex-sleep.service | inactive |
| bar | simple-sleep.service | inactive |
| bar | hirte-dep@simple-sleep.service | inactive |


### (D) Stopping the proxy (dependency) service on the target node

_Prerequisites:_ 

- Steps from (A)

_Steps:_

1. Using `hirtectl`, stop `hirte-dep@simple-sleep.service` on `agent bar`
2. Verify state 

_Expected Result:_

| agent | service | state |
|---|---|---|
| foo | compolex-sleep.service | inactive |
| foo | hirte-proxy@bar_compolex-sleep.service | inactive |
| bar | simple-sleep.service | active |
| bar | hirte-dep@simple-sleep.service | inactive |

### (E) Stopping the proxy (dependency) service on the target node with StopWhenUnneeded=yes

_Prerequisites:_ 

- Modify `simple-sleep.service`:
    - add `StopWhenUnneeded=yes` to the `[Unit]` section
    - systemctl daemon-reload
- Steps from (A)

_Steps:_

1. Using `hirtectl`, stop `hirte-dep@simple-sleep.service` on `agent bar`
2. Verify state 

_Expected Result:_

| agent | service | state |
|---|---|---|
| foo | compolex-sleep.service | inactive |
| foo | hirte-proxy@bar_compolex-sleep.service | inactive |
| bar | simple-sleep.service | inactive |
| bar | hirte-dep@simple-sleep.service | inactive |

**Comment by alexlarsson** [comment]
This is the basics, you want to also test other edge cases:

Depend on a service that doesn't exist should fail.
Depend on a service with a typo in the .service 
Depend on a service where the ExecStart=command fails.
Have two services on a node depend on a proxy, and ensure lifetimes still work
Have two services on two nodes depend on the same target service, ensure lifetimes still work.

**Comment by alexlarsson** [comment]
By "typo in the .service" i mean that the target service will have a typo inside the file, which will cause a different kind of failure codepath when loading it.

**Comment by Yarboa** [comment]
**Note:**
 @mwperina do we need to update e2e workflow to work with hirte-tests?

**Comment by Yarboa** [comment]
@engelmi Do you plan to work on it?
