### ISSUE TITLE
`hirtectl status  $node my.service`

### ISSUE THREAD

**Issue by rhatdan** [engelmi/hirte#255]
## Please describe what you would like to see

`hirtectl status  $node my.service`

## Please describe the solution you'd like

Hirte able to show the same output as systemctl status my.service on a remote machine.

## Please describe your use case

I believe this is required for the service broker to check status on services on the system.

I think we should at least be able to show whether a services exist, is enable, is running or is stopped.

**Comment by ygalblum** [comment]
During the development I found that in order to implement a full scale equivalent of `systemctl status` for `hirtectl`, a lot of code will be copied from the former into the hirte code base. As a result it was decided to scale down the implementation to align with the discussion in #281 

```
# hirtectl status laptop simple.service
UNIT              LOADED      ACTIVE     SUBSTATE    ENABLED
simple.service    loaded      inactive   dead        yes
```
