### ISSUE TITLE
CLI: Use getopt_long() instead of getopt() in order to support double dash arguments

### ISSUE THREAD

**Issue by sdunnagan** [engelmi/hirte#26]
This project has a good example of using getopt_long():
https://github.com/ericcurtin/twincam

**Comment by engelmi** [comment]
Would be great to have the following options 

- for the `node`:
```bash
--host : (instead of -h) the host to connect to
--port : (instead of -p) the port of the host

# optional:
-h --help: display usage help
```

- for the `orchestrator` (requires https://github.com/engelmi/orch/pull/24 to be merged):
```bash
--conf : (instead of -c) the path to the ini config
--port : (instead of -p) the port of the host

# optional:
-h --help: display usage help
```

What do you think? @mkemel 

_Tech hint:_
The example code is [here](https://github.com/ericcurtin/twincam/blob/main/src/twincam.cpp#L458-L574)

**Comment by mkemel** [comment]
#38
