### ISSUE TITLE
RFE: hirtectl list-nodes

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#291]
## Please describe what you would like to see

Would be nice to have a quick list  of nodes that hirte daemon is managing.

Example:
```
# hirtectl list-nodes [--filter]
Reporting hirte nodes at Tue May  9 17:14:19 UTC 2023
Name                   | Type                 |  IPv4 / IPv6                               | Status   
===================================================================================================
container-ASIL         | Control, Agent       | 172.77.2.1, fd00::4ce8:5bff:fe67:8c2d      | Online   
container-QM-node1     |  Agent               | 172.77.2.5, fd00::4ce8:5bff:fe67:8c5d      | Offline
container-QM-node2     |  Agent               | 172.77.2.2, fd00::4ce8:5bff:fe67:8c8d      | Online
container-QM-node3     |  Agent               | 172.77.2.3. fd00::4ce8:5bff:fe67:8c21      | Online
```

The fields are pretty much explained by itself. The `--filter` could be used like: `hiterctl list-nodes --filter=container-ASIL`

## Please describe your use case

Today there is no way to quick identify which nodes are working or not, need to look logs or dig config files and start pinging the hosts. Looking ahead in time, having such output in a sosreport from users (last time the report was generated (date/time)) and which nodes are working or not is super for support.

**Comment by dougsland** [comment]
We can even do like, instead of `--filter`, `--active (for online nodes)` or even both options as `filter` can be more grained option.

**Comment by engelmi** [comment]
What do you think about `hirtectl nodes [--filter]`? This would be similar to `podman images`

**Comment by dougsland** [comment]
We agreed that this one is likely be a dup of https://github.com/containers/hirte/issues/281
