### ISSUE TITLE
Please review e2e from containers/qm

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#298]
## Please describe what you would like to see

Recently we merged a tool to test https://github.com/containers/qm which execute **hirte** + **hirte-agent** behind the scenes in a nested container environment. 

If you are interested in maybe trigger this scenario in your E2E treadmill, please see more info here:
https://github.com/containers/qm/tree/main/tests/e2e

Feel free to close this report any time, as it is only a heads up.

**Comment by Yarboa** [comment]
@dougsland Can we close this one?

**Comment by dougsland** [comment]
@Yarboa sure, thanks for your work!
