### ISSUE TITLE
Default configuration should be loaded from source codes

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#301]
At the moment the default configuration is loaded from `/usr/share/{hirte|hirte-agent}/config/{hirte|agent}.conf`. Those files are included in relevant RPMs and as such they should not be modified by users. But they could be modified by package maintainers differently for each OS, which can introduced different default behaviour on each OS.

So the suggestion is:

1. Move default values for each option into relevant method(s) in https://github.com/containers/hirte/blob/main/src/libhirte/common/cfg.c
2. Reimplement all code parts to load the default value from configuration instead of having the default scattered all over the code
3. Comment out the values in `/usr/share/{hirte|hirte-agent}/config/{hirte|agent}.conf`, but continuing to load the file to ease the process of changing the default values for package maintainers in the different OS.

**Comment by rhatdan** [comment]
SGTM

**Comment by dougsland** [comment]
> At the moment the default configuration is loaded from `/usr/share/{hirte|hirte-agent}/config/{hirte|agent}.conf`. Those
> files are included in relevant RPMs and as such they should not be modified by users. But they could be modified by
> package maintainers differently for each OS, which can introduced different default behaviour on each OS.
> So the suggestion is:
> 
> 1. Move default values for each option into relevant method(s) in
> https://github.com/containers/hirte/blob/main/src/libhirte/common/cfg.c
> 2. Reimplement all code parts to load the default value from configuration instead of having the default scattered all over
> the code
> 3. Comment out the values in `/usr/share/{hirte|hirte-agent}/config/{hirte|agent}.conf` and stop loading this file upon start
> up

Even if the code has static default configuration the packagers can still workaround.
Example: packagers can workaround the static config loading via `%post` macro from `rpm spec` executing a sed command to replace the commented values in the config to some new "default values".  This will workaround the static config loading from the source.

**Comment by rhatdan** [comment]
I disagree with 3, the files should still be read on startup, but should be commented out by default.  If a distribution wants to change the defaults, they should be able to.  If the files do not exist at all, hirte and hirte-agent should be able to run.

**Comment by dougsland** [comment]
I am still not sure if worth doing such change. Loading from binary won't guarantee any rpm packager, distro or attacker can change the config files if it has privilegies and workaround this enforcement.  We should guarantee that when we have a release it has the proper validations like sha256sum and all distros are getting from the right channel.  Unfortunately, I think it will make more complex the software but it's up to you folks to decide.

/cc @pypingou for having more ideas.

**Comment by pypingou** [comment]
> Loading from binary won't guarantee any rpm packager, distro or attacker can change the config files if it has privilegies and workaround this enforcement

That's not the goal though.
The goal, as I understand it, is:
- We set defaults in the cod
- We provide a mechanism for packagers/distros to change these defaults using a file in `/usr/share/hirte...` (that'd be easier than doing sed command in `%prep`)
- We provide a mechanism for sysadmins to change these defaults using a file in `/etc/hirte/...` (which we would mark as `config(noreplace)` in the spec file).

**Comment by mwperina** [comment]
Updated the description according to the latest comments

**Comment by rhatdan** [comment]
Correct @pypingou. If a distro wants to ship with no config, they can and hirte and hirte-agent will still mostly work. Although you have to at least specify the managed nodes in hirte.conf.

**Comment by engelmi** [comment]
Has been solved in #394. Closing.
