### ISSUE TITLE
hirte system calls

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#343]
## Please describe what you would like to see

Goal1:  Identify hirte system calls and required libs during the execution. Keep a list of system calls from hirte available in the repo.
            Subtasks:
                 - Generate a document or markdown page with the list and path of execution
                 - Output must Plain Text **AND** machine language like JSON
             
Goal2: When a new PR is executed a CI job must detect if the PR includes a new system call not tracked yet.

There are tools and techniques to explore, example:
- strace
- ltrace
- ldd
- ftrace
- gdb
- static compilation
- evaluation based on tests/path flow

**Comment by dougsland** [comment]
Adding @engelmi in the loop.

**Comment by rhatdan** [comment]
First are we examining only hirte and hirte-agent, not hirtectl.  I think strace is fine.

**Comment by dougsland** [comment]
> First are we examining only hirte and hirte-agent, not hirtectl. 

correct

> I think strace is fine.

Okay, great.

**Comment by engelmi** [comment]
In order for this approach using `strace` to work, we'd need to ensure we have a (good enough) line coverage - ideally in an automated way and not setting up and running everything manual. Because of that, lets start with #397 to introduce test coverage collection in our unit/integration tests first. If we have the required test coverage, we should be able to simply add `strace` to the game - similar to #325. 
Since we need to do quite some preparation first, is it ok to close this issue (for now)? @dougsland

**Comment by dougsland** [comment]
> In order for this approach using `strace` to work, we'd need to ensure we have a (good enough) line
> coverage - ideally in an automated way and not setting up and running everything manual. Because
> of that, lets start with #397 to introduce test coverage collection in our unit/integration tests first. If
> we have the required test coverage, we should be able to simply add `strace` to the game - similar
> to #325. Since we need to do quite some preparation first, is it ok to close this issue (for now)?
> @dougsland

@engelmi I see https://github.com/containers/hirte/issues/397 as different task. Regarding running manually, I won't do that. I would use https://github.com/containers/qm/tree/main/tests/e2e to automate the deploy of hirte and friends and send commands to agent and manager trapping with strace. After the strace is done, we could analyze it and send the strace output / analyzer to github artifacts for download. In fact, that's what I would do. What's your thoughts on that?

**Comment by engelmi** [comment]
> send commands to agent and manager trapping with strace

That would be manual effort, which is not good on a changing code basis. 

Also, which commands would you send to hirte? Would you document them for reproducibility? Which code paths are executed? Depending on (external) preconditions you can get different results, e.g. is a monitor active for unit xyz. 
The integration tests need to be there anyway (and improved on) to have prove hirte is working properly. So these would be automatically send the commands to hirte. Wrapping this for example with strace is then rather simple and automated.

**Comment by dougsland** [comment]
> > send commands to agent and manager trapping with strace
> 
> That would be manual effort, which is not good on a changing code basis.
> 

I am not thinking in anything related manual.

Example:
- Use https://github.com/containers/qm/tree/main/tests/e2e to deploy environment (with or without QM)
- The hirte manager is listening via strace 
- Script a command via hirtectl to list units via systemd  

> Also, which commands would you send to hirte? Would you document them for reproducibility? 

Yes, see below.

> Which code paths are executed? Depending on (external) preconditions you can get different results, e.g. is a 
> monitor active for unit xyz.

We should cover all paths.
Going even more further in a possible implementation, which can be done via a "scenario" file:

Example scenario list units from systemd:
============================
**listunits.scenario** file:
```
[manager]
DEPLOY_ENV E2E  <---- pre-defined macro
CREATE hirte_daemon_straced.  <---- pre-defined macros

[client]
LIST_UNITS_MANAGER. <---- pre-defined macro
LIST_UNITS_AGENT        <--- pre-defined macro
(alternative, users can use python/bash commands  in the client)
/path/foobar/tests/list_units
```
A bash script or python could read this and generate such environment and we will track this scenario output. This approach could be used in a generic track/tests.


> The integration tests need to be there anyway (and improved on) to have prove hirte is working properly. So
> these would be automatically send the commands to hirte. Wrapping this for example with strace is then rather
> simple and automated.

I am not saying integration tests shouldn't be done, more tools we have, more higher we can fly. :)
