### ISSUE TITLE
make tests requirement for new PRs

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#344]
## Please describe what you would like to see

If possible, let's make new PRs (specially new RFEs) to write tests **a requirement**  (before merging).
I know, it take more time and sometime is boring but it helps the software maturity and also could help us understand the system calls flow (https://github.com/containers/hirte/issues/343). We have in house @engelmi which has showed a bunch of ninja testing code in C to help us achieve this goal.

**Comment by engelmi** [comment]
Would be great! Although I think we need to check this on each PR review manually.

**Comment by dougsland** [comment]
In general a good feedback received, let's keep it up. No action needed, closing.
