### ISSUE TITLE
Move fmt and lint to meson

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#36]
## Please describe what you would like to see

Instead of using makefile targets for formatting and linting (`make fmt` and `make lint`), these tasks should be integrated into meson to have a single tool for running everything. 

## Please describe the solution you'd like

One way to achieve this could be to move the current makefile targets to bash scripts (e.g. `hack/fmt.sh`, `hack/lint.sh`, etc.) and create a meson target as described [here](https://mesonbuild.com/Run-targets.html). For example, having the target
```bash
run_target('fmt',  command : 'hack/fmt.sh')
```
would be called like this:
```bash
meson compile fmt
```

AC:
- Makefile removed
- formatting (+check) can be triggered via meson
- linting (+auto fix) can be triggered via meson
- CI steps are updated

**Comment by eli-schwartz** [comment]
Actually Meson already has clang-format and clang-tidy support built in, and can automatically create targets to run them for you. However, it doesn't use the names "fmt" and "lint".

- `ninja clang-format`
- `ninja clang-format-check`
- `ninja clang-tidy`

There's no clang-tidy-fix target generated though.

**Comment by engelmi** [comment]
Hi @eli-schwartz, 
thank you! I tried to use `ninja` as you proposed. For `clang-format` and `clang-format-check` this seems to work pretty well.  For `clang-tidy`, however, we would need to exclude the `src/ini/ini.c` file (at least for now). I know via the [.clang-format-ignore](https://mesonbuild.com/Code-formatting.html) directories and files can be excluded from formatting - is similar way for `clang-tidy`?

Edit: I think something like `ninja clang-tidy-fix` (similar to `clang-tidy --fix`) would be an awesome feature :)

**Comment by eli-schwartz** [comment]
>  I know via the `.clang-format-ignore` directories and files can be excluded from formatting - is similar way for `clang-tidy`?

Yes. In fact it uses the same backend code for both, so `.{tool}-include` will select the globs that meson will iterate over, and `.{tool}-ignore` will add exclusions to those globs, and then meson will run the `{tool}` once for each file on the final file list.
