### ISSUE TITLE
Remove network dependency in get_address_test

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#398]
## Describe the bug

`get_address` internally uses of `getaddrinfo` to get hints to use either IPv4 or IPv6. While this is fine to use in production, its not a good practice to use in tests since it might fail due to "outside" conditions. For example, if there is no dns resolution, the `get_address_test` fails due to a timeout as can be seen in the following output: 

```bash
get_address_test time out (After 30 seconds)
11/11 get_address_test     TIMEOUT        30.04s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=154 /builddir/build/BUILD/hirte-0.4.0/redhat-linux-build/src/libhirte/test/common/network/get_address_test
Summary of Failures:
11/11 get_address_test     TIMEOUT        30.04s   killed by signal 15 SIGTERM
```

## To Reproduce

Running `meson test -C builddir` with no dns resolution active on the machine. 

## Expected behavior

Either a passing or disabled `get_address_test`. 

## Proposal to fix

Create a type that is matching the `getaddrinfo` and having it being passed in as function pointer. This way the caller can determine the behavior of the function. For the production code, just pass the original `getaddrinfo`. For the test code, just implement a dummy function that sets the `res->ai_family` and `res->ai_addr` and pass it to the call. 
If that is not possible or too complicated, lets deactivate the test for now (removing from the list in meson.build).

**Comment by Yarboa** [comment]
@engelmi Consider having another container to use as dns server

**Comment by mwperina** [comment]
> @engelmi Consider having another container to use as dns server

We can't do this in various build systems (for example brew), we need to disconnect code within unit tests from the actual resolver functionality. Because we don't need to test resolver functionality, we need to test our code on top of resolver results.

**Comment by dougsland** [comment]
back to hirte bits, let me see what's going on here.

**Comment by engelmi** [comment]
@dougsland Please see the proposal to fix this issue.

**Comment by dougsland** [comment]
Trying a local reproducer disabling the resolver.

```
# cat /etc/resolv.conf
#search dns.podman
#nameserver fd00::1:8:1
#nameserver 10.90.0.1

# ping redhat.com
ping: redhat.com: Name or service not known

# make clean
find . -name \*~ -delete
find . -name \*# -delete
meson setup --wipe builddir || true
The Meson build system
Version: 0.63.3
Source dir: /root/test-hirte/hirte
Build dir: /root/test-hirte/hirte/builddir
Build type: native build
Project name: hirte
Project version: 0.5.0
C compiler for the host machine: cc (gcc 11.4.1 "cc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)")
C linker for the host machine: cc ld.bfd 2.35.2-42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-cast-function-type: YES
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency libsystemd found: YES 252
Configuring config.h using configuration
Configuring org.containers.hirte.conf using configuration
Configuring org.containers.hirte.Agent.conf using configuration
Program go-md2man found: YES (/usr/bin/go-md2man)
Program clang-tidy found: YES (/usr/bin/clang-tidy)
Build targets in project: 25

Found ninja-1.10.2 at /usr/bin/ninja

# meson test -C builddir
ninja: Entering directory `/root/test-hirte/hirte/builddir'
[37/37] Linking target src/libhirt...ommon/network/assemble_tcp_address
 1/11 cfg_test                     OK              0.04s
 2/11 list_test                    OK              0.03s
 3/11 parse-util_test              OK              0.03s
 4/11 string-util_test             OK              0.03s
 5/11 time-util_test               OK              0.03s
 6/11 is_ipv4_test                 OK              0.02s
 7/11 is_ipv6_test                 OK              0.02s
 8/11 get_address_test             OK              0.02s
 9/11 assemble_tcp_address         OK              0.02s
10/11 get_log_timestamp            OK              0.01s
11/11 get_time_seconds             OK              0.01s

Ok:                 11
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /root/test-hirte/hirte/builddir/meson-logs/testlog.txt
```

**Comment by engelmi** [comment]
> Trying a local reproducer disabling the resolver.
> ...

I don't think only removing entries from `/etc/resolv.conf` will result in `getaddrinfo` to block indefinitely (which the logs of the test run also show). If you want to reproduce this issue, you don't need to have `getaddrinfo` fail, but rather block. I haven't looked into reproducing this issue, but maybe setting up a custom dns server with a delay (>30s) as @Yarboa suggested might be a possible approach. Again, the main issue is that `getaddrinfo` is a blocking call (at least how we use it) and since it might do so indefinitely it causes then the timeout for the meson test. 
Update: Maybe we should change the `get_address` implementation as well to not block indefinitely in certain cases. But thats a topic for the future.
