### ISSUE TITLE
Add support for daemon-reload

### ISSUE THREAD

**Issue by pypingou** [engelmi/hirte#399]
It could be interesting to have hirte (and thus the different hirte-agent) support doing `systemd daemon-reload`.
For example, if new quadlet files are installed into different nodes, hirte could then be used to reload systemd and restart the services, thus allowing to make use of these new services.

**Comment by engelmi** [comment]
@pypingou Is `hirte` also supposed to do this automatically, e.g. by detecting a newly added quadlet file, or is it sufficient to provide a public D-Bus API on hirte so it can be called (e.g. via `hirtectl`)?

**Comment by pypingou** [comment]
I'd say the later :)

**Comment by engelmi** [comment]
Ah ok :) In that case, #322 implemented a `Reload` method on the D-Bus API. 
Example usage of the API using 
`hirtectl`:
```bash
hirtectl daemon-reload laptop
```

`pyhirte`:
```python
from pyhirte.api import Node
n = Node("laptop")
n.reload()
```
Closing this issue.

**Comment by pypingou** [comment]
Perfect, thanks!
