### ISSUE TITLE
RFE: show hirte client version when connected to the manager and vice versa

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#424]
## Please describe what you would like to see

Long term RFE but would be nice to show in the logs of the `hirte manager` like:

**Manager side, information about client**:
```
./builddir/src/manager/hirte -c /etc/hirte/hirte.conf
2023-08-01 19:29:34,642+0000 INFO	: Starting hirte 0.5.0
2023-08-01 19:26:14,045+0000 INFO	: Registered managed node from fd 8 as 'qm.control' **agent version 0.4.0** <---- here
2023-08-01 19:26:14,046+0000 INFO	: Registered managed node from fd 9 as 'control' **agent version 0.5.0**. <------ here
```

**Client side, information about manager**:
```
builddir/src/agent/hirte-agent -c /etc/hirte/agent.conf
2023-08-01 19:32:41,840+0000 INFO	: Starting hirte-agent 0.5.0
2023-08-01 19:32:41,847+0000 INFO	: Connecting to manager on tcp:host=10.90.0.56,port=842 **version 0.5.0**
2023-08-01 19:32:41,847+0000 INFO	: Manager version detected as 0.5.0 <-------- here
2023-08-01 19:32:41,848+0000 INFO	: Connected to manager as 'node1'
```

**Comment by ArtiomDivak** [comment]
I have a few questions. Is it possible that the agent will be a different version from the manager? (Because the version of the agent and hirte are taken from the same global variable).
Would you like for me to work on it? It seems reasonable but it's better if others will see it too.

**Comment by dougsland** [comment]
> I have a few questions. Is it possible that the agent will be a different version from the manager? (Because the
> version of the agent and hirte are taken from the same global variable). Would you like for me to work on it? It
> seems reasonable but it's better if others will see it too.

Great questions @ArtiomDivak and agreed, we need more inputs from the others developers too.

Answering your question (from my point of view): 
In a "perfect scenario" would be manager and agents using the same version. However, I don't believe all nodes can update in the same time. This scenario might generate some kind of incompatible settings and/or communication failures. If we can see in the logs which version tried to communicate with each other  (client and manager) would be nice. 

Now, if hirte manager and hirte agent should **only work** with the same version, we should make a `hirte_log_infof()` call informing that when we detect it. 

@mwperina @rhatdan could clarify this.

**Comment by rhatdan** [comment]
I don't think they would ever be a different version, I see no reason for that.

**Comment by dougsland** [comment]
> I don't think they would ever be a different version, I see no reason for that.

@rhatdan how about a new release of hirte? All nodes can be upgraded at the same time ?

**Comment by mwperina** [comment]
Let's not overcomplicate things, I don't see a reason why we should report a version of a component from a different node.  Administrator of the whole system can use RPM to check which version is installed on each node and he should manage the whole upgrade of the system on multiple nodes to not forgot about any upgrades

**Comment by engelmi** [comment]
Can we close this issue since we are probably not going to implement it?

**Comment by dougsland** [comment]
Sure.
