### ISSUE TITLE
Quay repo does not contain integration-test-base:latest arm image 

### ISSUE THREAD

**Issue by Yarboa** [engelmi/hirte#437]
## Describe the bug

Running e2e tests is failing while running on arm machine 

## To Reproduce

Run e2e tests against arm HW 
or run the following script
podman build -f ./containers/$CONTAINER_USED -t $HIRTE_IMAGE_NAME .

## Expected behavior
podman build -f ./containers/$CONTAINER_USED -t $HIRTE_IMAGE_NAME .
shuld build image successfully

**Comment by Yarboa** [comment]
There are two issues here
1) inspect quay.io/hirte/integration-test-base:latest
Isnot multi arch
Need to add manifests arm64 and amd64
https://docs.podman.io/en/latest/markdown/podman-manifest.1.html

It is working on my personal repo 
https://quay.io/repository/yarboa/integration-test-base
Need to push it to hirte

~2) The fixes are not working while running on arm machines~

**Comment by engelmi** [comment]
> Isnot multi arch

Yes, there is no manifest pushed to any of the repos in https://quay.io/organization/hirte/. Updating images is currently using the build triggers provided by quay. I am not sure if it is possible to add a manifest via this trigger. If not (what I think is most likely), we have to move from quay's build trigger to a gh action that builds and pushes the images as well as the manifest. Shouldn't be that much effort, I'll have a look at it. 

> Need to add manifests arm64 and amd64

Are there any other platforms we need to support? @Yarboa

**Comment by engelmi** [comment]
@Yarboa Could you check again? 
While migrating to the new organization I also added a manifest for both, amd64 and arm64, as you can see here: 
https://quay.io/repository/bluechi/integration-test-base?tab=tags

**Comment by Yarboa** [comment]
This returns 
```
podman manifest inspect \
> quay.io/bluechi/integration-test \
> | grep architecture

```
Error: reading image "docker://quay.io/bluechi/integration-test:latest": reading manifest latest in quay.io/blue
chi/integration-test: unauthorized: access to the requested resource is not authorized

**Comment by engelmi** [comment]
> 



> This returns
> 
> ```
> podman manifest inspect \
> > quay.io/bluechi/integration-test \
> > | grep architecture
> ```
> 
> Error: reading image "docker://quay.io/bluechi/integration-test:latest": reading manifest latest in quay.io/blue chi/integration-test: unauthorized: access to the requested resource is not authorized

I think you need to inspect `quay.io/bluechi/integration-test-base` @Yarboa

**Comment by Yarboa** [comment]
Yes, this one is ok
somehow i get the following error 
```
 podman run -it localhost/bluechi-image:v1 \                                 
> /bin/bash 
```

returns an error 
{"msg":"exec container process `/bin/bash`: Exec format error","level":"error","time":"2023-08-29T18:55:46.95705
1Z"} 

as per this 
https://github.com/containers/podman/blob/main/troubleshooting.md#27-exec-container-process-binsh-exec-format-error-or-another-binary-than-binsh

I am looking at dependencies 

podman inspect \
> quay.io/centos/centos:stream9 \
>  | grep architecture

return no arch

**Comment by engelmi** [comment]
So that error means that the pulled image is not an arm64 one, if I understand correctly? Hmm... maybe we build the multiplatform images wrong... I'll have a look as well. 


> podman inspect \
>
>    quay.io/centos/centos:stream9
>    | grep architecture
> 
> return no arch

Using 
```bash
podman manifest inspect quay.io/centos/centos:stream9
```
should include the architectures.

**Comment by engelmi** [comment]
This should be fixed now, so I am closing it. 
If not, please reopen it @Yarboa
