### ISSUE TITLE
Rename Hirte to BlueChi RPM packages

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#448]
## Describe the bug

Rename Hirte to BlueChi RPM packages:

- All existing hirte packages will be rename to corresponding bluechi packages
- New bluechi packages should obsolete corresponding hirte packages to provide smooth upgrade path

**Comment by pypingou** [comment]
Moving this to 0.6 since we won't be able to do this rename before we have a BlueChi release.

**Comment by mwperina** [comment]
> Moving this to 0.6 since we won't be able to do this rename before we have a BlueChi release.

What's the reason for it? bluechi 0.5.0 release will already have all RPMs renamed ...

**Comment by pypingou** [comment]
> What's the reason for it? bluechi 0.5.0 release will already have all RPMs renamed ...

It won't since there will be no blue 0.5 before 0.5 is released :)

I guess it depends if you're seeing ticket as "the list of things to do before we release version X" or if you see them differently.

**Comment by pypingou** [comment]
But I'm re-opening this ticket as it is more work than just renaming the spec files and adjusting it

**Comment by mwperina** [comment]
All package renames is finished, closing
