### ISSUE TITLE
Rename Hirte to BlueChi in python generator and pyhirte

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#451]
## Describe the bug

 - Rename generator part
 - Rename pyhirte to bluechi
 - Publish bluechi to PIP
 - Update PI information that pyhirte is obsoleted by bluechi

**Comment by mwperina** [comment]
Reopening, as we still need to:

- Create a new package `bluechi` in PIP
- Update `pyhirte` information that it's obsoleted by `bluechi`

**Comment by engelmi** [comment]
Moving this to milestone v0.6 since the v0.5 release is required for it.

**Comment by engelmi** [comment]
The new python bindings for v0.5.0 have been published under the new project name: https://pypi.org/project/bluechi/
The old bindings (https://pypi.org/project/pyhirte/) has been deprecated and changed so it requires `bluechi` on install - so even if `pip install pyhirte` is run, it'll install the required bluechi bindings.
