### ISSUE TITLE
Migrate current COPR snapshot builds to packit

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#452]
## Describe the bug

We are building and publishing snapshot builds https://copr.fedorainfracloud.org/coprs/mperina/hirte-snapshot/
There are currently 2 problems with COPR:

- It's hard to create and maintain organization in COPR
- If we need to check packaging issues on Fedora/EPEL or different platforms, which are not available on GitHub CI, we need to wait till the change is merged and then check COPR

We may try to switch to https://packit.dev/ which should provide all those missing features.

And also it PackIT approach works, we don't need to handle renaming Hirte to BlueChi in COPR

**Comment by dougsland** [comment]
+1 

/cc @Yarboa
