### ISSUE TITLE
hirte -v should include the commit hash 

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#454]
## Describe the bug

The team is working in the 0.5.0 release which is not tagged or completed. However, if you do hirte -v is shows 0.5.0 but as we 
don't have an official release we have no idea which commit is based, "everything is 0.5.0".

As reference, this commit seems very useful for using meson/script/versioning:
https://github.com/martinpitt/umockdev/pull/189/commits/c41a95d7d96391e45a95a07c4000e7d89e98ff02

**Comment by engelmi** [comment]
In production, any released version would point to a specific commit - so this would be a feature used purely development, in my point of view. Not sure if this is really needed since a developer knows which commit he used to built the project. 
What do you think? @mkemel @mwperina

**Comment by dougsland** [comment]
> In production, any released version would point to a specific commit - so this would be a feature used purely
> development, in my point of view. Not sure if this is really needed since a developer knows which commit he
> used to built the project. What do you think? @mkemel @mwperina

This is normal procedure in several open source projects. When doing a release, just set hash var to empty and [make a release](https://github.com/containers/bluechi/commit/b3f4bfa3f381d40472261aae6fa161ff7892e34b). After that, use the [Post commit schema](https://github.com/containers/bluechi/commit/b3f4bfa3f381d40472261aae6fa161ff7892e34b) that bluechi already uses and set it back.
