### ISSUE TITLE
make test: ninja: error: unknown target 'coverage-html'

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#461]
## Describe the bug

**make test** works but is failing in the end with `ninja: error: unknown target 'coverage-html'`:

```
# make test 
<SNIP>
meson test -C builddir
ninja: Entering directory `/root/test/bluechi/builddir'
ninja: no work to do.
 1/11 cfg_test                     OK              0.04s
 2/11 list_test                    OK              0.04s
 3/11 parse-util_test              OK              0.03s
 4/11 string-util_test             OK              0.03s
 5/11 time-util_test               OK              0.03s
 6/11 is_ipv4_test                 OK              0.02s
 7/11 is_ipv6_test                 OK              0.02s
 8/11 get_address_test             OK              0.02s
 9/11 assemble_tcp_address         OK              0.02s
10/11 get_log_timestamp            OK              0.01s
11/11 get_time_seconds             OK              0.01s

Ok:                 11
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /root/test/bluechi/builddir/meson-logs/testlog.txt
ninja coverage-html -C builddir
ninja: Entering directory `builddir'
ninja: error: unknown target 'coverage-html'
make: *** [Makefile:19: test] Error 1
```

**Comment by dougsland** [comment]
Please wait https://github.com/containers/bluechi/pull/460 get merged to work on this to avoid conflict. Hopefully, should be merged soon.

**Comment by mwperina** [comment]
You need to install `gcovr` package:

```
dnf install -y gcovr
```

**Comment by dougsland** [comment]
> You need to install `gcovr` package:
> 
> ```
> dnf install -y gcovr
> ```
Thanks @mwperina, CentOS 9 Stream don't have such package. For CentOS 9 Stream `pip install gcovr` works. However, the `make test` script must be smart enough to detect if the gcovr is available or not and suggest users to `pip install or dnf install` instead of error message.

**Comment by dougsland** [comment]
something like:
```
SOME_COMMAND := some_command

check_command:
    @if ! command -v $(SOME_COMMAND) > /dev/null; then \
        echo "$(SOME_COMMAND) is not available. Please install it."; \
        exit 1; \
    fi
```

and in the target:

```test: check_command```

**Comment by mwperina** [comment]
On CentOS Stream 9 you can use lcov instead:
```
dnf install -y epel-release
dnf install lcov
```

I would not invest to improve Makefile, it should just be a "stupid" layer on top of meson, so we may just need to update README.developer.md:

1. Add additional packages there or
2. Move code coverage into separate Makefile target with additional section about lcov/gcov dependencies

**Comment by dougsland** [comment]
> On CentOS Stream 9 you can use lcov instead:
> 
> ```
> dnf install -y epel-release
> dnf install lcov
> ```
> 
> I would not invest to improve Makefile, it should just be a "stupid" layer on top of meson, so we may just need to update README.developer.md:
> 
> 1. Add additional packages there or
> 2. Move code coverage into separate Makefile target with additional section about lcov/gcov dependencies

I meant, I would prefer to have a fix in meson somehow, I need some time to see if this is possible. I am sure, as soon @engelmi is back from his deserved vacation he can share some magic trick in meson.

**Comment by eli-schwartz** [comment]
> I meant, I would prefer to have a fix in meson somehow, I need some time to see if this is possible. I am sure, as soon @engelmi is back from his deserved vacation he can share some magic trick in meson.

What would be the magic trick? Meson generates developer targets for coverage, if the coverage tools are installed. What should Meson do when the coverage tools are *not* installed?
- Generate the developer targets as no-ops that error out? So `ninja coverage-html` will still fail, but for a different reason.
- Generate the developer targets as no-ops that silently exit after doing nothing? So people actually trying to get coverage will think they got it, only it never ran?

**Comment by dougsland** [comment]
> > I meant, I would prefer to have a fix in meson somehow, I need some time to see if this is possible. I am sure,
> as soon @engelmi is back from his deserved vacation he can share some magic trick in meson.
> 
> What would be the magic trick?

Show the users the proper error message and exit.

> Meson generates developer targets for coverage, if the coverage tools are installed. What should Meson do
> when the coverage tools are _not_ installed?
> 
> * Generate the developer targets as no-ops that error out? So `ninja coverage-html` will still fail, but for a
> different reason.
> * Generate the developer targets as no-ops that silently exit after doing nothing? So people actually trying to
> get coverage will think they got it, only it never ran?

I did some research tonight and here my proposal to users with proper error message:

```
# git diff
diff --git a/meson.build b/meson.build
index 32f4aa4..6e33d2f 100644
--- a/meson.build
+++ b/meson.build
@@ -13,6 +13,11 @@ project(
   ]
 )

+gcovr = find_program('gcovr', required: false)
+if not gcovr_bin.found()
+   find_program('lcov', required: true)
+endif
+
 test_cflags = [ '-Wno-cast-function-type' ]

 cc = meson.get_compiler('c')
```

Example:
```
The Meson build system
Version: 1.0.1
Source dir: /root/bluechi-rename-c/bluechi
Build dir: /root/bluechi-rename-c/bluechi/builddir
Build type: native build
Project name: bluechi
Project version: 0.5.0
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)")
C linker for the host machine: cc ld.bfd 2.39-9
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program gcovr found: NO
Program lcov found: NO

../meson.build:18:3: ERROR: Program 'lcov' not found or not executable.   <-------- HERE

A full log can be found at /root/bluechi-rename-c/bluechi/builddir/meson-logs/meson-log.txt
FAILED: build.ninja
/usr/bin/meson --internal regenerate /root/bluechi-rename-c/bluechi /root/bluechi-rename-c/bluechi/builddir
ninja: error: rebuilding 'build.ninja': subcommand failed
make: *** [Makefile:17: test] Error 1
```

**Comment by eli-schwartz** [comment]
What, why?

You don't need the coverage tools installed if you as a user just plan to build the project and install it.

You only need it if you plan to generate coverage reports, which most people don't.

**Comment by dougsland** [comment]
> What, why?
> 
> You don't need the coverage tools installed if you as a user just plan to build the project and install it.
> 
> You only need it if you plan to generate coverage reports, which most people don't.

Indeed, we should improve `make test` to not require coverage reports and only print the reports if the tools are available in the system or create a specific target for that (test + report).

**Comment by engelmi** [comment]
How to use unit tests is described in the [readme's unit test section](https://github.com/containers/bluechi/blob/main/README.developer.md#unit-tests) - which can be enhanced by adding that coverage tool `gcov` or `lcov` is required. I don't want to provide an automatic mechanism to check or install these tools - just read the doc. 
Regarding the make target: Either we rename the it (e.g. to sth like `test-with-coverage`) or remove the `ninja` command.

@dougsland Could you submit a small PR to update the readme (and optionally change the make target)?

**Comment by dougsland** [comment]
Rejected by https://github.com/containers/bluechi/pull/436
