### ISSUE TITLE
Change the project license to LGPL-2.1-or-later

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#462]
Hi all,
We would like to contribute BlueChi project to Eclipse Foundation and as a part of the contribution process we were encouraged to change project license to LGPL-2.1-or-later to ease the contribution process.
In order to change project license we need a consent from all project contributors:

- [x] Ygal Blum
- [x] Sandro Bonazzola
- [x] Pierre-Yves Chibon
- [x] Ed Chong
- [x] Artiom Divak
- [x] Steve Dunnagan
- [x] Michael Engel
- [x] Veronika Fuxova
- [x] Mark Kemel
- [x] Minsoo Kim
- [x] Douglas Schilling Landgraf
- [x] Alexander Larsson
- [x] Lokesh Mandvekar
- [x] Martin Perina
- [x] Yariv Rachmani
- [x] Erik Sjölund
- [x] Petr Šplíchal
- [x] Paul Wallrabe
- [x] Daniel Walsh

Please add your agreement or disagreement with the license change by placing a comment to this issue.

**Comment by mwperina** [comment]
I agree with proposed license change

**Comment by lsm5** [comment]
I'm not active on this project, but I agree FWIW.

**Comment by eriksjolund** [comment]
I agree with proposed license change

**Comment by dougsland** [comment]
All good +1

**Comment by ygalblum** [comment]
I agree with proposed license change

**Comment by engelmi** [comment]
I agree with the proposed license change

**Comment by pypingou** [comment]
I agree with the change

**Comment by raballew** [comment]
I agree with the proposed license change.

**Comment by Darth-Mera** [comment]
I agree with the proposed change

**Comment by ArtiomDivak** [comment]
I agree with the proposed license change

**Comment by alexlarsson** [comment]
I agree with proposed license change

**Comment by pypingou** [comment]
@sandrobonazzola @psss @ewchong ping :)

**Comment by rhatdan** [comment]
I agree with the license change.

**Comment by ewchong** [comment]
I agree with the proposed license change.

**Comment by psss** [comment]
I agree with the license change.

**Comment by sandrobonazzola** [comment]
I agree with the license change

**Comment by mkemel** [comment]
I agree with the license change

**Comment by sdunnagan** [comment]
I agree with proposed license change

**Comment by mwperina** [comment]
Adding @irishair according to agreement in https://github.com/containers/bluechi/pull/489#issuecomment-1689233641

**Comment by Yarboa** [comment]
I agree with the proposed license change.
