### ISSUE TITLE
bluechictl start a failing service reports "done"

### ISSUE THREAD

**Issue by pypingou** [engelmi/hirte#467]
## Describe the bug

When starting a service, via bluechictl, that will automatically/directly fail, it reports "done" even though the service never ran.

Do we want to keep this behavior as is or can we improve it?

## To Reproduce

Please provide the steps to reproduce the issue.

1. Create the following systemd service:
```
# cat /etc/systemd/system/false.service 
[Unit]	
Description=test

[Service]
ExecStart=/bin/false
Type=simple
```
2. Reload systemd (systemctl daemon-reload)
3. Start bluechi and bluechi-agent
4. Start the service using bluechictl: `hirtectl start laptop false.service`

/!\ this behavior is also true if you `ExecStart` a path that doesn't exist: `/bin/fake`

## Current behavior
```
# hirtectl start laptop false.service
Unit false.service start operation result: done
# hirtectl status laptop false.service
UNIT		| LOADED	| ACTIVE	| SUBSTATE	| ENABLED	|
--------------------------------------------------------------------------------
false.service	| loaded	| failed	| failed	| static	|
```

## Expected behavior

Please describe what you would expect to happen.

I'm not sure what we want to do here, but not finding that the service failed to start from the get go seems a little odd

**Comment by alexlarsson** [comment]
This is a complex area in systemd behaviour. Unless there is a syntax error in the unit file, the Start() operation generally reports that the start succeeds if it successfully created and scheduled a Start job. If you are interested also in the result of the job you need to listed to the job signals.

We should make `bluechictl start` mirror the exact behaviour of `systemctl start` here.

**Comment by alexlarsson** [comment]
Its possible that we need to add the code to bluechictl to actually follow the job progress, if that is what systemctl does.

**Comment by pypingou** [comment]
> We should make bluechictl start mirror the exact behaviour of systemctl start here.

Yeah, although:
```
# systemctl start false
# echo $?
0
# systemctl status false
× false.service - test
     Loaded: loaded (/etc/systemd/system/false.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Wed 2023-08-16 17:11:42 CEST; 2s ago
```

**Comment by alexlarsson** [comment]
Also, systemctl has a related `--no-block` option that we should maybe also support.

**Comment by alexlarsson** [comment]
Maybe `--wait` is insteresting too.

**Comment by pypingou** [comment]
```
# systemctl start false --wait
# echo $?
1
```
That does look better :)

**Comment by rhatdan** [comment]
Yes seems Wait would be the wait to handle this.

**Comment by rhatdan** [comment]
In one case the unit file fails, in the other case the application running within the unit file fails.

The interesting thing about the --wait, would be it will only wait for notify services, correct?

**Comment by rhatdan** [comment]
```
ExecStart=bash -c "sleep 10; exit 5"
```
What happens if you ran a unit file like above?

**Comment by pypingou** [comment]
> ```
> ExecStart=bash -c "sleep 10; exit 5"
> ```
> 
> What happens if you ran a unit file like above?

The usual approach:
```
# systemctl start false
# echo $?
0
# systemctl status false
● false.service - test
     Loaded: loaded (/etc/systemd/system/false.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Thu 2023-08-17 09:45:25 CEST; 6s ago
...
# systemctl status false
× false.service - test
     Loaded: loaded (/etc/systemd/system/false.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Thu 2023-08-17 09:45:35 CEST; 522>
```

With `--wait`:
```
# systemctl start false --wait
<waited the 10 seconds before coming back>
# echo $?
1
# systemctl status false
× false.service - test
     Loaded: loaded (/etc/systemd/system/false.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Thu 2023-08-17 09:46:41 CEST; 10s ago
```

So `--wait` isn't ideal either, we don't want to wait for seconds/minutes until, maybe, the service crashes

**Comment by alexlarsson** [comment]
I'm not sure what the goal is of this issue. hirte behaves just like systemctl, because that is how systemd works.

I think the main misunderstanding is the what was expected in terms of startup of this example service. This is a service with `Type=simple`, which is described like this (from systemd.service manpage):

> service manager will consider the unit started immediately after the main service process has been forked off

systemd waits until the service is "started", which (as per above) is at fork, not after fork has run for a bit, and then starts exec() of the binary.

If the goal is to have `systemctl start` to wait (and related stuff, like delaying start of dependencies) until the process is initialized somehow , then you have to somehow tell systemd how to detect that initialization is done. There are multiple types for this, such as `Type=forking` (wait until service daemonizes) or `Type=notify` (daemon calls sd_notify() when done).

**Comment by pypingou** [comment]
I've found out that `Type=notify` does what is expected in the case of `/bin/false` (for `sleep 10 && false` it still waits 10 seconds before raising the error).

I am slowly reaching the conclusion that there may not be anything for us to change here and the issue may be more that we're running into some of the finer details of systemd that we need to learn more.

**Comment by alexlarsson** [comment]
@pypingou You can't just set `Type=notify` on `/bin/false`. It is not a service that calls sd_notify() when it has initialized itself.

**Comment by rhatdan** [comment]
Right if you did Type=notify with sleep inf, then the service would never be reported started I believe, or systemd would kill it after timeout (90 Seconds?)
