### ISSUE TITLE
Change the license of API usage examples 

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#474]
Hi all,
we would like to change the license of API usage examples inside `doc/api-examples` directory to [CC0-1.0](https://spdx.org/licenses/CC0-1.0.html) license to ease the reuse of those examples for the community.
In order to change the API usage examples license we need a consent from all contributors to those examples:

- [x] Ygal Blum
- [x] Pierre-Yves Chibon
- [x] Michael Engel
- [x] Douglas Schilling Landgraf
- [x] Alexander Larsson
- [x] Martin Perina

Please add your agreement or disagreement with the license change by placing a comment to this issue.

**Comment by mwperina** [comment]
I agree with license change

**Comment by engelmi** [comment]
I agree with the license change

**Comment by alexlarsson** [comment]
I agree with the license change

**Comment by ygalblum** [comment]
I agree with the license change

**Comment by pypingou** [comment]
I agree with the license change

**Comment by dougsland** [comment]
I agree with the license change
