### ISSUE TITLE
Change the license of the Python bluechi module examples

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#477]
Hi all,
we would like to change the license of Python bluechi module examples inside `doc/bluechi-examples` directory to [CC0-1.0](https://spdx.org/licenses/CC0-1.0.html) license to ease the reuse of those examples for the community.
In order to change the Python bluechi module examples license we need a consent from all contributors to those examples:

- [x] Michael Engel
- [x] Douglas Schilling Landgraf

Please add your agreement or disagreement with the license change by placing a comment to this issue.

**Comment by engelmi** [comment]
I agree with the proposed license change

**Comment by dougsland** [comment]
I agree with the proposed license change
