### ISSUE TITLE
Cannot use RPMs build locally on Fedora 37 on tmt tests

### ISSUE THREAD

**Issue by ygalblum** [engelmi/hirte#535]
## Describe the bug

Building the RPMs locally on Fedora 37 creates a dependency on python 3.11 for bluechi-python. However, the tmt tests run on CentoOS Stream 9 containers which run python 3.9. As a result, the test container fails to build 

## To Reproduce

Follow the steps in the tests' README file for running locally built RPMs

## Expected behavior

The tests are able to run (regardless to success of failure of them)

**Comment by ygalblum** [comment]
@Yarboa FYI

**Comment by mwperina** [comment]
It's expected that you build RPMs on the same OS, which you run the integration test on. [README.md](https://github.com/containers/bluechi/blob/main/tests/README.md) contains steps for CS9, but similar steps could be done also on Fedora if you want to run integrations tests on Fedora.

**Comment by Yarboa** [comment]
> @Yarboa FYI

There is option:
https://github.com/containers/qm/tree/main/tests/e2e#run-tmt-tests-framework-locally
You need to build the rpms inside the vm, I do not like it though.

But let me try to find reasonable solution for Fedora

**Comment by ygalblum** [comment]
@mwperina the integration tests are containerized and therefore, the developer does not control on which O/S the tests will run. Since the containers are based on CentOS9, the RPMs must be built on CentOS9.
Now, since developers usually do not develop on CentOS, I think it's fair to assume that they will encounter this issue. Therefore, I think we should look into providing a means to build the RPMs needed by the tests.
