### ISSUE TITLE
Does bluechi-agent send signal on disconnect?

### ISSUE THREAD

**Issue by pypingou** [engelmi/hirte#543]
I know that bluechi will send a signal on the system's dbus instance if it looses connection with one of its agent.
What about the other way around: does an agent send a signal on the system's dbus instance if it looses a connection to bluechi?

The use-case is as such:
Imagine a zonal architecture, where one zone looses connection with the main ECU. That would be a network connectivity issue, not a full system crash (or it could be a full system crash but of the main ECU then). The ECU running the agent could have an "Emergency state manager" responsible for moving that ECU/zone into a "safe" mode until the entire system has recovered.

**Comment by dougsland** [comment]
both sending signal seems good to me and the car manufacture control software can take actions.

**Comment by engelmi** [comment]
> What about the other way around: does an agent send a signal on the system's dbus instance if it looses a connection to bluechi?

Currently, on a disconnect the agent would try to reconnect again in an interval defined by the [heartbeat interval](https://bluechi.readthedocs.io/en/latest/man/bluechi_agent_conf/#heartbeatinterval-long). In case we lose connection and reconnect again, we can simply mirror the behavior of the controller and emit a similar signal to the system D-Bus of the agent machine. This will require a code change and is not only about documentation, though. 
What do you think? @pypingou

**Comment by pypingou** [comment]
That's pretty much what I had in mind yeah: have bluechi-agent signal where it is running that it has lost connection to the primary node, in the same way that bluechi does it on that node.

And we should document both of these :)

**Comment by engelmi** [comment]
Sounds good :) Then for this issue its basically 
~~- [ ] Add a `NodeConnectionStateChanged` signal to the agent, which gets emitted each time the agent dis-/connects~~
~~- [ ] Extend the mkdocs about the state change signal for both, controller and agent~~

~~In addition to the `NodeConnectionStateChanged` signal, it probably makes sense to also mirror the `Status` and `LastSeenTimestamp` properties like they are available through the controller (see [here](https://github.com/containers/bluechi/blob/main/data/org.eclipse.bluechi.Node.xml#L68-L69)) in case the listener for this state change signal registered too late and missed it. This can be done in a follow-up issue to keep the scope limited.
What do you think? @pypingou @alexlarsson~~

**Update:** see https://github.com/containers/bluechi/issues/543#issuecomment-1710305484

**Comment by pypingou** [comment]
> What do you think? 

Sounds good to me! :)

**Comment by alexlarsson** [comment]
I don't think bluechi is the right place to handle catastrophic events like two ECUs totally becoming  disconnected. All sorts of other things will break as well then, and I don't think it is reasonable to try to locally "work around" it.

However, I don't mind having a signal for the agent state on the local bus. It is easy to do, and if someone finds value in it, good for them.

**Comment by pypingou** [comment]
On Thu, Sep 07, 2023 at 01:34:14AM -0700, Alexander Larsson wrote:
> I don't think bluechi is the right place to handle catastrophic events like two ECUs totally becoming  disconnected. All sorts of other things will break as well then, and I don't think it is reasonable to try to locally "work around" it.

I don't see this any different from the notification bluechi sends to the state
manager. This should be monitored in other places as well anyway and detected
there as well.
The idea with our signals, I think, it to provide another mechanism to notify
that something is going wrong and maybe BlueChi will be the first to notice,
maybe it won't (depending on when each watchdog triggers).

**Comment by engelmi** [comment]
I discovered that the `NodeConnectionStateChanged` signal is a duplicate since we actually emit connection state changes via the `Status` property of the node: 
https://github.com/containers/bluechi/blob/v0.5.0/src/manager/node.c#L76

I created 
- #549 to extend the D-Bus API description with documentation comments as well as the annotation for `org.freedesktop.DBus.Property.EmitsChangedSignal`
- #550 extend the generator to use the enhanced documentation and provide easy to use functions for listing to those property state changes

After those two issue, the `Status` property from the controller can be mirrored to the agent and the `NodeConnectionStateChanged`signal be replaced (#551).

**Comment by engelmi** [comment]
Reopening since mkdocs documentation is missing.

**Comment by engelmi** [comment]
This has been documented in https://github.com/containers/bluechi/pull/563 (using the D-Bus API) and https://github.com/containers/bluechi/pull/595 (one of the getting started examples on using bluechictl). 
Closing.
