### ISSUE TITLE
Optimize LastTimeSeen property

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#552]
## Please describe what you would like to see

Currently, the manager is setting the `last_seen` property of a node each time a heartbeat is received successfully from that node (see [here](https://github.com/containers/bluechi/blob/v0.5.0/src/manager/node.c#L497)). Since the property for the timestamp ([here](https://github.com/containers/bluechi/blob/v0.5.0/src/manager/node.c#L77)) is marked as `SD_BUS_VTABLE_PROPERTY_EXPLICIT`, it makes sense to only set `last_seen` when a node disconnects and return on an explicit property query the current time (when online) or `last_seen` (when offline). 
This reduces the number of (regular) operations a bit.

**Comment by pypingou** [comment]
test (sorry for the noise)

**Comment by engelmi** [comment]
Closing in favor of https://github.com/eclipse-bluechi/bluechi/issues/857
