### ISSUE TITLE
Change license of API usage examples

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#557]
Hi all,
[CC0-1.0](https://spdx.org/licenses/CC0-1.0.html) is a license that Fedora doesn't really like (see [here](https://docs.fedoraproject.org/en-US/legal/license-approval/#_allowed_for_content)). Therefore, we would like to change the license of API usage examples inside `doc/api-examples` and `doc/bluechi-examples` directories to [MIT-0](https://opensource.org/license/mit-0/) license.
In order to change the API usage examples license we need a consent from all contributors to those examples:

- [x] Ygal Blum
- [x] Pierre-Yves Chibon
- [x] Michael Engel
- [x] Douglas Schilling Landgraf
- [x] Alexander Larsson
- [x] Martin Perina

Please add your agreement or disagreement with the license change by placing a comment to this issue.

**Comment by engelmi** [comment]
I agree with the license change

**Comment by pypingou** [comment]
I agree with the license change

**Comment by mwperina** [comment]
I agree with the license change

**Comment by dougsland** [comment]
I agree with the license change

**Comment by alexlarsson** [comment]
I agree

**Comment by ygalblum** [comment]
I agree with the license change
