### ISSUE TITLE
Add API examples for C/C++

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#565]
## Please describe what information you were trying to find

In https://github.com/containers/bluechi/pull/563, the structure for the BlueChi D-Bus API examples of bindings in different languages has been restructured. It would be great to add the missing examples in `C/C++`. 

The `C/C++` sample code files should be put into the following directory: 
https://github.com/containers/bluechi/blob/main/doc/api-examples/c/

Checklist of missing examples:

- [x] enable-unit
- [x] get-cpuweight
- [x] list-nodes
- [x] list-node-units
- [x] monitor-agent-connection
- [x] monitor-node-connections
- [x] monitor-unit
- [x] set-cpuweight
- [x] start-unit

The setup on how to run the examples has been written in the [setup.md](https://github.com/containers/bluechi/blob/main/doc/api-examples/c/setup.md). 

After adding all missing examples, the setup as well as all files can be linked in the [doc/docs/api/examples.md](https://github.com/containers/bluechi/blob/main/doc/docs/api/examples.md).

**Comment by engelmi** [comment]
@dougsland Would you like to take this task? :)

**Comment by dougsland** [comment]
> @dougsland Would you like to take this task? :)

if not urgent, sure thing. :)

**Comment by raballew** [comment]
Adding C++ examples seems to be a reasonable thing to do in the short term, as a lot of software in those regulated contexts is written in C++. C examples already exist at https://github.com/eclipse-bluechi/bluechi/tree/main/src/client (at least to some extend). Could we bump the priority of this issue if it is a reasonable amount of effort?

**Comment by engelmi** [comment]
The amount of effort for it should be rather low. I added it to the new milestone.
