### ISSUE TITLE
Add API examples for Rust

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#566]
## Please describe what information you were trying to find

In https://github.com/containers/bluechi/pull/563, the structure for the BlueChi D-Bus API examples of bindings in different languages has been restructured. It would be great to add the missing examples in `Rust`. 

The `Rust` sample code files should be put into the following directory: 
https://github.com/containers/bluechi/blob/main/doc/api-examples/rust/

Checklist of missing examples:

- [x] enable-unit
- [x] get-cpuweight
- [x] list-nodes
- [x] list-node-units
- [x] monitor-agent-connection
- [x] monitor-node-connections
- [x] monitor-unit
- [x] set-cpuweight
- [x] start-unit

The setup on how to run the examples has been written in the [setup.md](https://github.com/containers/bluechi/blob/main/doc/api-examples/rust/setup.md). 

After adding all missing examples, the setup as well as all files can be linked in the [doc/docs/api/examples.md](https://github.com/containers/bluechi/blob/main/doc/docs/api/examples.md).

**Comment by engelmi** [comment]
@dougsland Would you like to take this task? :)

**Comment by dougsland** [comment]
> @dougsland Would you like to take this task? :)

if it's not urgent, sure. 👍
