### ISSUE TITLE
Improve error messages returned from D-Bus API

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#567]
Currently, some of the D-Bus error messages returned from BlueChi provide little to no information what went wrong so that the caller has a hard time figuring out what exactly went wrong, e.g. 

- https://github.com/containers/bluechi/blob/main/src/manager/manager.c#L662
Returns `Internal error` when the structure of the message is actually wrong. So returning `SD_BUS_ERROR_INVALID_ARGS` with a message like `Invalid arguments` would be easier to understand as caller. 
- https://github.com/containers/bluechi/blob/main/src/manager/monitor.c#L348
`Unsubscribe` returns only `Internal error` when it actually couldn't find the subscription to remove. 
- another example is the `Internal error` when listing units via `bluechictl` described in #568

*Acceptance criteria:*
Checking at least all public BlueChi API methods and changing the error type and message to provide a better understanding what went wrong.

**Comment by Iiqbal2000** [comment]
Hi @engelmi, Can I take this issue?

**Comment by engelmi** [comment]
Hi @Iiqbal2000, sure thing :) I'll assign this issue to you. If you need any support, don't hesitate to reach out :)

**Comment by Iiqbal2000** [comment]
Thank you @engelmi for assigning this to me. I'll start working on it and review the mentioned parts of the code.

**Comment by Iiqbal2000** [comment]
I still wondering how to decide the flags based on the error returned by D-Bus, could you explain it?

@engelmi @dougsland

**Comment by engelmi** [comment]
> I still wondering how to decide the flags based on the error returned by D-Bus, could you explain it?

Can you provide an example? I am not sure what flags you mean. Is it like the `sd_bus_reply_method_errorf`, e.g. [an example here](https://github.com/containers/bluechi/blob/main/src/agent/agent.c#L698)?

**Comment by Iiqbal2000** [comment]
The flag I'm referring to is `SD_BUS_ERROR_INVALID_ARGS`. How do we determine the flags for the second argument of `sd_bus_reply_method_errorf`?

Based on my understanding, when we input DBUS arguments as demonstrated in the following function, the argument is `s`:
https://github.com/containers/bluechi/blob/e1aa265039a7b4a6264251aa1fedbce75ee99271/src/manager/monitor.c#L283

If it error we always use `SD_BUS_ERROR_INVALID_ARGS` on `sd_bus_reply_method_errorf`

https://github.com/containers/bluechi/blob/e1aa265039a7b4a6264251aa1fedbce75ee99271/src/manager/monitor.c#L285

**Comment by engelmi** [comment]
In general, the second argument of `sd_bus_reply_method_errorf` should be a descriptive message of what went wrong - so that the caller of the API can take appropriate action. 

The example of `sd_bus_message_enter_container` you mentioned above happens in the context of subscribing to a list of units. Currently, we only provide `Invalid arguments` as a message. This could be improved to
```C
return sd_bus_reply_method_errorf(m, 
    SD_BUS_ERROR_INVALID_ARGS, 
    "Failed to read list of unit subscriptions: %s", strerror(-r)
);
```
So when calling the API and receiving that error we know something failed when reading the list. And by providing the error code message via `strerror(-r)` we get additional information, e.g. we might have sent a just a simple string and no list (`ENXIO`). 

The same can be applied to `sd_bus_message_read`, of course. For example [here](https://github.com/containers/bluechi/blob/main/src/manager/monitor.c#L268-L272): 
```C
// instead of
return sd_bus_reply_method_errorf(
                                m, SD_BUS_ERROR_INVALID_ARGS, "Invalid arguments: %s", strerror(-r));

// we know we failed to read the node parameter, therefore:
return sd_bus_reply_method_errorf(
                                m, SD_BUS_ERROR_INVALID_ARGS, "Invalid argument for the node name: %s", strerror(-r));
```

Does this clarify your question? @Iiqbal2000

**Comment by Iiqbal2000** [comment]
I got your point
