### ISSUE TITLE
Adding ECA validation

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#596]
In order to adhere to the [committer guidelines from Eclipse](https://www.eclipse.org/legal/committerguidelines.php#contributions), we need to add an ECA validation:

```
1. validation of pull request contributors against our Eclipse Foundation Contributor Validation service.
2. validation of pull request contributors for an Eclipse Specification Project.
3. validation of “Signed-off-by” footers in commit messages for non-committers.
```

- [x] I'd propose to setup the app provided by [EclipseFdn](https://github.com/EclipseFdn) for this: https://github.com/apps/eclipse-eca-validation
- [x] In addition, we'll need a documentation for new contributors on what to do and how to sign it, e.g. via a `CONTRIBUTING.md`

**Comment by mwperina** [comment]
Isn't the 2nd task fixed by https://github.com/eclipse-bluechi/bluechi/pull/774 ? Or anything else missing?

@engelmi

**Comment by engelmi** [comment]
You are right. Its already done in https://github.com/eclipse-bluechi/bluechi/pull/774. Closing.
