### ISSUE TITLE
Configuration files are not read from root directory

### ISSUE THREAD

**Issue by Yarboa** [engelmi/hirte#620]
## Describe the bug

Recently QM CI was failing, 
The following PR fixed configuaration file locations 

Please refer this REVIEW
https://github.com/containers/qm/pull/255#pullrequestreview-1698977239

```
rpm -qa | grep bluechi
bluechi-selinux-0.6.0-0.202310231038.git48f4a85.el9.x86_64
bluechi-agent-0.6.0-0.202310231038.git48f4a85.el9.x86_64
bluechi-controller-0.6.0-0.202310231038.git48f4a85.el9.x86_64
bluechi-ctl-0.6.0-0.202310231038.git48f4a85.el9.x86_64
```

## To Reproduce

1. Set controller configuration files under /etc/bluechi/controller.conf
2. Restart 
3. Anonymous request appear, 
systemctl status bluchi-controller

## Expected behavior

As per man page this location should be readable also

**Comment by engelmi** [comment]
@Yarboa When was the last successful CI run? My first assumption it that this is linked to the `bluechi` -> `bluechi-controller` renaming. 

From what I know `/etc/bluechi/controller.conf.d/` should be the correct path for dropping custom configs. Please make sure: 
- that there are no other config files in the conf.d directory or ensure that your file has a name that leads it to be listed last (conf files are read one after the other from top to bottom and overwrite previous settings, see [loading order](https://bluechi.readthedocs.io/en/latest/configuration/#loading-order))
- that the config for the controller contains the ini section `[bluechi-controller]` (v0.6) instead of `[bluechi] ` (v0.5).

**Comment by Yarboa** [comment]
Thanks, @engelmi 
Please refer this date 
https://github.com/containers/qm/pull/252
So i think it is a bug in manpages, isnt it? 
PTAL 

> man bluechi-controller.conf | grep -A 4 FILE
> FILES
>        Distributions provide the /usr/share/bluechi/config/controller.conf  file  which  de‐
>        fines   bluechi   configuration  defaults.  Administrators  can  copy  this  file  to
>        /etc/bluechi/controller.conf and specify their own configuration.
>

**Comment by engelmi** [comment]
Thanks @Yarboa 
Ok, so the date is from after the rename. But in-between nothing changed for the man pages or the implementation regarding any configuration code as far as I can see. 
Based on 
```C
// https://github.com/containers/bluechi/blob/main/src/libbluechi/common/cfg.h#L44
#define CFG_ETC_BC_CONF CONFIG_H_SYSCONFDIR "/bluechi/controller.conf"
```
and 
```C
result = cfg_load_complete_configuration(
                        manager->config, CFG_BC_DEFAULT_CONFIG, CFG_ETC_BC_CONF, CFG_ETC_BC_CONF_DIR);
```
I am quite sure that `/etc/bluechi/controller.conf` is being read. 

Could you verify the possible root causes I mentioned above? @Yarboa

**Comment by Yarboa** [comment]
PTAL here https://github.com/containers/qm/pull/255/checks?check_run_id=18064200047
The only place that configuration file returned to its previous file location
++ eval 'podman exec                    control                    bluechictl                    list-units                    qm-node1 
AllowedNodes   does not contain the change  qm-node1 


Maybe it is worth adding configuration tests

I see that tests using this directory
https://github.com/containers/bluechi/blob/main/tests/bluechi_test/config.py#L24

https://github.com/containers/bluechi/blob/cecc21ccf814efd4961235f73fba6f38f58b39a0/src/libbluechi/common/cfg.c#L121C5-L121C36

I will search for logs in controller

**Comment by Yarboa** [comment]
@engelmi  BUG in QM scripts, sorry for the headache
