### ISSUE TITLE
Integration tests for uncovered cases

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#668]
By implementing https://github.com/eclipse-bluechi/bluechi/issues/397 we are able to collect the overall code coverage when all integration tests are run. The latest results were compressed into the following tarball: [2023-12-14-report.tar.gz](https://github.com/eclipse-bluechi/bluechi/files/13684952/report.tar.gz)

Based on this report, the following cases are not yet covered and integration tests for those should be written:
- [x] Agent reconnect (https://github.com/eclipse-bluechi/bluechi/pull/669)
When reconnecting, the agent doesn't fail at least once, even though that this once intended in [test node reconnect](https://github.com/eclipse-bluechi/bluechi/tree/main/tests/tests/tier0/monitor-node-reconnect)
- [x] Agent using a config file from the `-c` cli option
Could be tested for *3* cases - config is valid, invalid (file doesn't exist) and key-value pair is invalid (e.g. `NodeName`, missing the `=` char)
https://github.com/eclipse-bluechi/bluechi/pull/677
https://github.com/eclipse-bluechi/bluechi/pull/680
- [x] Controller using a config file from the `-c` cli option
Could be tested for *3* cases - config is valid, invalid (file doesn't exist) and key-value pair is invalid (e.g. `AllowedNodeNames`, missing the `=` char)
https://github.com/eclipse-bluechi/bluechi/pull/677
https://github.com/eclipse-bluechi/bluechi/pull/680
- [x] Agent connects to controller via `ControllerAddress` 
https://github.com/eclipse-bluechi/bluechi/pull/741
- [x] Function `ReloadUnit` is used
Could be tested by creating two systemd services. The first would define an `ExecReload=systemctl start <other service>`. 
https://github.com/eclipse-bluechi/bluechi/pull/775
- [x] Function `DaemonReload` is used
Could be tested by creating a systemd services manually, running bluechictl daemon-reload and then checking if new unit exists 
https://github.com/eclipse-bluechi/bluechi/pull/818
- [x] Function `ListUnits` (on manager to list all units for all nodes) is used
https://github.com/eclipse-bluechi/bluechi/pull/760
- [x] Disable collecting metrics again
Either the existing test (see [metrics-start-unit test](https://github.com/eclipse-bluechi/bluechi/tree/main/tests/tests/tier0/metrics-start-unit)) can be extended or a new test can be written
- [x] Function `SetLogLevel` is used
This has to be tested for the manager (`org.eclipse.bluechi.Manager SetLogLevel`) and the agent (`org.eclipse.bluechi.Node SetLogLevel`)
  https://github.com/eclipse-bluechi/bluechi/pull/723
  https://github.com/eclipse-bluechi/bluechi/pull/736
- [x] Agent is stopped while Proxy Service(s) are active

*Note:* The list above is not complete. Quite some code parts are error case handling, e.g. for OOM which is really hard to test.

**Comment by mwperina** [comment]
@mkemel

**Comment by ArtiomDivak** [comment]
A little comment

**Comment by engelmi** [comment]
All tests have been added. Closing.
