### ISSUE TITLE
bluechictl: add specific usage functions for each method

### ISSUE THREAD

**Issue by mkemel** [engelmi/hirte#691]
## Please describe what you would like to see

Currently, calling `bluechictl command --help` for any command shows the same as calling `bluechictl --help` - overall usage for bluechi. The new bluechictl Command and Method interfaces allow defining a separate usage print function for each command, see `methods[]` array in `client/main.c`.

## Please describe the solution you'd like

Implement a separate usage function for each method, replacing `usage_bluechi`, e.g. `usage_list_untis`, `usage_start`, `usage_stop`, etc. This function should print usage examples, available options and flags for this method, etc. You can see how podman CLI works in that regard for reference.

**Comment by engelmi** [comment]
This has been done in https://github.com/eclipse-bluechi/bluechi/pull/941.
Closing.
