### ISSUE TITLE
Manager.ListNodes should return IP addresses of the nodes

### ISSUE THREAD

**Issue by mkemel** [engelmi/hirte#701]
## Please describe what you would like to see

org.eclipse.bluechi.Manager.ListNodes method should return the addresses of the Nodes, and `bluechictl status` will display them (as requested in #281).
```
NODE       STATE       LAST SEEN        IP
laptop     online      now              10.0.2.2
pi         offline     never       
```

**Comment by dougsland** [comment]
this is interesting one, depending of urgency I can add into my backlog. @engelmi

**Comment by engelmi** [comment]
> this is interesting one, depending of urgency I can add into my backlog. @engelmi

Sure :) As soon as you have time you can start working on it.
