### ISSUE TITLE
Add watch option to bluechictl status

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#706]
## Please describe what you would like to see

In #700 a watch option for `bluechictl status` was added to continuously monitor the status of the system (all nodes) or one specific node. This option, however, is not yet implemented for getting the status of a specific unit, e.g. `bluechictl status laptop cow.service -w` - which prints out the status of the unit as expected, but doesn't honor the `-w` option. 

## Please describe the solution you'd like

Implement the watch option `-w` for getting the status of a unit on a specific node, e.g. `bluechictl status laptop cow.service`.

**Comment by ArtiomDivak** [comment]
Please assign me to this issue.

**Comment by engelmi** [comment]
Done in https://github.com/eclipse-bluechi/bluechi/pull/865. Closing.
