### ISSUE TITLE
Duplicate function in code coverage HTML report

### ISSUE THREAD

**Issue by ArtiomDivak** [engelmi/hirte#713]
## Describe the bug

Currently, in the flow of code coverage, we use the host to merge all the info files which may cause 
various LCOV versions to be used. This causes the duplication of functions in the report HTML file.

## To Reproduce

1. Make sure that LCOV 2.01 is used on your PC and LCOV 1.14 is used in the integration container
2. Run integration test with code coverage option as described in https://github.com/eclipse-bluechi/bluechi/tree/main/tests

## Expected behavior

No duplication of functions is supposed to be seen inside the report HTML

**Comment by engelmi** [comment]
@ArtiomDivak 
To be sure that `lcov` on the host isn't used, we'd need to remove it from the workflow: https://github.com/eclipse-bluechi/bluechi/blob/main/.github/workflows/integration-tests.yml#L58

**Comment by engelmi** [comment]
This should've been fixed in #719, right? @ArtiomDivak
