### ISSUE TITLE
Getting started for setting up BlueChi via ansible collection

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#725]
## Please describe what information you were trying to find

We recently released an Ansible Collection for BlueChi: https://galaxy.ansible.com/ui/repo/published/eclipse_bluechi/bluechi/

It would be great to have a getting started guide on mention it and demonstrate how it can be used to setup a BlueChi system.

**Comment by dougsland** [comment]
I am interested in learn this new feature, assigning to me.
