### ISSUE TITLE
Add integration test for bluechictl metrics listen

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#783]
Add integration test, which will verify `bluechictl metrics listen` functionality

**Comment by mwperina** [comment]
Is it possible to assume that following methods will also be covered by this test?

* match_start_unit_job_metrics_signal
   https://github.com/eclipse-bluechi/bluechi/blob/main/src/client/method-metrics.c#L32
* match_agent_job_metrics_signal
   https://github.com/eclipse-bluechi/bluechi/blob/main/src/client/method-metrics.c#L60

**Comment by mkemel** [comment]
Yes, they will
