### ISSUE TITLE
Add integration test for bluechictl status -w

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#785]
Add integration test(s) to verify `bluechictl status -w` functionality.

**Comment by mkemel** [comment]
Do we need a separate issue for `bluechictl status -w` and `bluechictl status <node> -w`? This would cover two missing functions in `method-status.c` @mwperina

**Comment by mkemel** [comment]
`bluechictl status <node> <unit>` was already covered by https://github.com/eclipse-bluechi/bluechi/issues/830

`bluechictl status -w` on the other hand was not yet covered. Renaming and taking over
