### ISSUE TITLE
Cover passing command line arguments for bluechi-agent in tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#787]
Cover passing following command line arguments for bluechi-agent in tests:

* `-n`/`--name`
* `-H`/`--host`
* `-a`/`--address`
* `-i`/`--interval`
* `-p`/`--port`
* `-u`/`--user`

**Comment by mkemel** [comment]
All arguments but `-u/--user` were covered by #894 
`-u/--user` will be covered in #799
