### ISSUE TITLE
Cover function `proxy_service_method_error` from `src/agent/proxy.c` in tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#788]
Cover function [proxy_service_method_error](https://github.com/eclipse-bluechi/bluechi/blob/main/src/agent/proxy.c#L187) from `src/agent/proxy.c` in tests

**Comment by engelmi** [comment]
This is related to https://github.com/eclipse-bluechi/bluechi/issues/797 and will be covered in the same test.
