### ISSUE TITLE
Cover function `controller_method_ping` from `controller/controller.c` by tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#790]
Cover function [controller_method_ping](https://github.com/eclipse-bluechi/bluechi/blob/main/src/controller/controller.c#L453C12-L453C34) from `controller/controller.c` by either unit or integration tests

**Comment by engelmi** [comment]
This method we can remove, its is automatically implemented on the `org.freedesktop.DBus.Peer` our custom ping method serves no purpose.
