### ISSUE TITLE
Implement (and cover by tests) or remove function `job_method_cancel` from `controller/job.c`

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#793]
Either implement and cover by unit or integration tests function [job_method_cancel](https://github.com/eclipse-bluechi/bluechi/blob/main/src/controller/job.c#L147) or remove the function completely

**Comment by engelmi** [comment]
Implementing job cancel should forward the cancel to the agent where it calls:
```org.freedesktop.systemd1 /org/freedesktop/systemd1 /org/freedesktop/systemd1/job/<job id>```
(and probably doing some additional operations like cleanup)

Also, this should probably be run in `node_shutdown` along with `agent_request_cancel` - although we'd need to investigate how these two relate. 

The integration test for this could use the following systemd unit:
```systemd
[Unit]
Description=A very simple service
[Service]
Type=simple
ExecStartPre=/bin/sleep 1000
ExecStart=/bin/true
```
By using the sleep in `ExecStartPre=`, systemd doesn't consider the service running for x seconds so the job is pending and can be canceled.

**Comment by engelmi** [comment]
Done in #821
