### ISSUE TITLE
Cover function `proxy_monitor_send_error` from `controller/proxy_monitor.c` by tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#797]
Cover function [proxy_monitor_send_error](https://github.com/eclipse-bluechi/bluechi/blob/main/src/controller/proxy_monitor.c#L168) by either unit or integration tests.

**Comment by engelmi** [comment]
This is being called in two cases:
- the requesting service requires the proxy on a node that isn't connected to the controller
- OOM occurs further down in the execution

Since the second case can't be tested easily, testing the first case is sufficient.
