### ISSUE TITLE
Cover function `method_peer_hello` from `libbluechi/bus/bus.c` by tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#798]
Cover function [method_peer_hello](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/bus/bus.c#L89) by unit or integration tests

**Comment by engelmi** [comment]
~This is just a dummy method and can be removed.~

After quickly cross-checking, it seems that the hello method is specified in the standard:
https://dbus.freedesktop.org/doc/dbus-specification.html (under "Message Bus Messages")
So we should probably keep it and do a simple call to it in an integration test (e.g. via `busctl`).
