### ISSUE TITLE
Cover function `user_bus_open` from `libbluechi/bus/bus.c` by tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#799]
Cover function [user_bus_open](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/bus/bus.c#L270) by unit or integration tests

**Comment by mwperina** [comment]
Could it be covered this along with `-u`/`--user` test for bluechi https://github.com/eclipse-bluechi/bluechi/issues/787 ?

**Comment by engelmi** [comment]
> Could it be covered this along with `-u`/`--user` test for bluechi #787 ?

For `bluechi-agent` yes. For `bluechi-controller`, however, it is set at compile-time. But for the test of using the user bus, this should be fine. For `root` the user bus isn't set as far as I remember, so this might be difficult to test.

**Comment by mwperina** [comment]
I think testing with bluechi-agent is enough, user bus should not be used in production anyway
