### ISSUE TITLE
Sorry for the question, but what is the purpose of the project?

### ISSUE THREAD

**Issue by ghost** [engelmi/hirte#80]
?

SystemD code-style and DBus referrence prompts to the thought that it is a container orchestartor leveraging systemd as container workload manager and DBus as control plane message bus?

**Comment by pypingou** [comment]
That'd be a good thought :)

**Comment by mwperina** [comment]
We have added a brief project description to README.md and there will be follow up presentations, so closing the issue for now

**Comment by rhatdan** [comment]
@pypingou you have some good slides that show an overall design of `hirte`, I would love to get those into the projects README.md
