### ISSUE TITLE
Cover function `bc_log_to_stderr_full_with_location` from `libbluechi/log/log.c` by tests

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#806]
Cover function [bc_log_to_stderr_full_with_location](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/log/log.c#L102) by either unit or integration tests

**Comment by engelmi** [comment]
It is not worth writing a dedicated test for it. The related function `bc_log_to_journald_with_location` is "tested" implicitly by all unit tests since logging to journald is default. So changing a few tests to use stderr instead of journald is enough.
