### ISSUE TITLE
Investigate why functions `bc_log_get_log_fn` and `bc_log_get_quiet` are not reported as covered

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#807]
Investigate why function [bc_log_get_log_fn](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/log/log.c#L150) and [bc_log_get_quiet](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/log/log.c#L166) when they are used in https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/test/log/bc_log_init_test.c

**Comment by engelmi** [comment]
Most probably related to #804.
