### ISSUE TITLE
RFE: Switch controller host

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#819]
## Please describe what you would like to see

The `bluechi-controller` is currently a single point of failure. In order to address this issue and increase the resilience of the system, `bluechi-agent` should provide an API method to set the [ControllerAddress=](https://github.com/eclipse-bluechi/bluechi/blob/main/config/agent/agent.conf#L23-L26) which triggers a disconnect in the agent and emits a signal that the address has been changed.

**Note:**
Addressing the leader election (e.g. via [raft algorithm](https://raft.github.io/)) and ensuring that the controller switch for all agents is "atomic" (i.e. not ending up in a partitioned state) will be delegated to an external component. 
The change is not persisted, so on a restart the agent will connect to the previously configured controller. 

## Please describe the solution you'd like

In order to enable switching the `bluechi-controller` via API we need:
- [x] a new API method `SwtichController(dbus_address: str)` (https://github.com/eclipse-bluechi/bluechi/pull/839)
- [x] a new property for the assembled [orch_addr](https://github.com/eclipse-bluechi/bluechi/blob/main/src/agent/agent.h#L64) which emits a changed signal when changed (https://github.com/eclipse-bluechi/bluechi/pull/839)
- [x] integration tests are implemented (https://github.com/eclipse-bluechi/bluechi/pull/872)
- [x] python API bindings are updated (https://github.com/eclipse-bluechi/bluechi/pull/839)
- [x] documentation has been updated (https://github.com/eclipse-bluechi/bluechi/pull/839)

The spec of API method would look like this:
```xml
<method name="SwitchController">
    <arg name="dbus_address" type="s" direction="in" />
</method>
```
Where `dbus_address=tcp:host=127.0.0.1,port=842`, for example. 

And the spec of the property on `orch_addr` like this:
```xml
<property name="ControllerAddress" type="s" access="read">
    <annotation name="org.freedesktop.DBus.Property.EmitsChangedSignal" value="true" />
</property>
```

**Comment by mwperina** [comment]
Original comment is not relevant anymore to updated description

**Comment by alexlarsson** [comment]
I don't see the advantage of having each node specify the list of possible controllers. If you have this external entity doing the switch it already knows the actual address of the consensus. Having to map it to the bluechi-agent configured id is just extra work. 

I think we just need an option to change the dbus address of the controller, and a signal for when it changes. (And maybe a property so we can read it).

**Comment by dofmind** [comment]
External entity like the leader election should know the controller list that bluechi-agent has on configuration, to map to use which controller. I think it should need a D-Bus API to get the controller list on configuration from bluechi-agent.

**Comment by alexlarsson** [comment]
Yeah, this new API looks good to me.

**Comment by dofmind** [comment]
Looks good to me the new API but how about add a option to reconnect right away like https://github.com/eclipse-bluechi/bluechi/pull/761? Even if bluechi-controller is failed, bluechi-agent takes some time to aware of disconnection with bluechi-controller - about 1 ~ 2 minutes.

**Comment by engelmi** [comment]
> Looks good to me the new API but how about add a option to reconnect right away like https://github.com/eclipse-bluechi/bluechi/pull/761? Even if bluechi-controller is failed, bluechi-agent takes some time to aware of disconnection with bluechi-controller - about 1 ~ 2 minutes.

The reconnect would happen right away. When calling `SwitchAddress(addr: string)`, the agent sets the new address and calls `disconnect`, which triggers a reconnect to the controller with the new address. I think a flag for `reconnect` is not necessary - you'd want to switch controller directly when the method is called.

**Comment by engelmi** [comment]
@dofmind Would you be up for adding an integration test for the new `SwitchController` feature?

**Comment by dofmind** [comment]
@engelmi Sure, i will try.
