### ISSUE TITLE
Run multihost tests on testing farm

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#841]
## Please describe what you would like to see

In #662 we added multihost support for the integration tests. It would be good to provide means to run (trigger) the tests in a multihost setup on testing farm via GitHub Action. Triggering this workflow should be limited to the project committers (which should be by default) and, as a first step, manually starting them would suffice. 

Note: Currently, multihost is only supported for Red Hat Ranch (see https://docs.testing-farm.io/Testing%20Farm/0.1/test-request.html#_current_limitations)

**Comment by Yarboa** [comment]
@engelmi is there future option to run it on TestingFarm public ranch?

**Comment by engelmi** [comment]
> @engelmi is there future option to run it on TestingFarm public ranch?

It is not supported on Public Ranch according to [testing farm limitations](https://docs.testing-farm.io/Testing%20Farm/0.1/test-request.html#_current_limitations). As soon as this limitation isn't valid anymore, we can run them on public ranch as well.
