### ISSUE TITLE
`bluechictl status <node> <units>` does not accept multiple units

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#869]
## Describe the bug

Currently, the [src/client/method-status.c](https://github.com/eclipse-bluechi/bluechi/blob/main/src/client/method-status.c) does not accept multiple units for `bluechictl status <node> <unit1> <unit2> ...` and simply fails. This is due to the switch in `method_status(...)`:
https://github.com/eclipse-bluechi/bluechi/blob/main/src/client/method-status.c#L647-L660

`argc` is larger than 2 if multiple units are being passed to the bluechictl status command. 

## To Reproduce

Setting up `bluechi-controller` and `bluechi-agent` and running

```bash
bluechictl status <node> <unit1> <unit2>
```

## Expected behavior

The command should show the status for all units listed.

**Comment by ArtiomDivak** [comment]
Hi please add me to the assignment

**Comment by engelmi** [comment]
Fixed in https://github.com/eclipse-bluechi/bluechi/pull/871. Closing.
