### ISSUE TITLE
Pick a nice default port for the agent to connect to.

### ISSUE THREAD

**Issue by alexlarsson** [engelmi/hirte#87]
I just picked a random one (808) for HIRTE_DEFAULT_PORT. We should figure out what a good option to use is.

**Comment by mwperina** [comment]
Suggestion: let's try to convert the name hirte to number using phone dialer: https://www.vectorstock.com/royalty-free-vector/smartphone-keypad-dialer-with-buttons-user-vector-23259942

That gives us:

    h - 4
    i - 4
    r - 7
    t - 8
    e - 3

That gives us either 44783 or 4783, which are both unassigned.

**Comment by pypingou** [comment]
Closed as duplicate of: https://github.com/containers/hirte/issues/87

**Comment by pypingou** [comment]
Proposal: 842
