### ISSUE TITLE
Integration Test for proxy service propagation is flaky

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#874]
## Describe the bug

The integration test `proxy-service-propagate-target-service-failure` is flaky. 
One of the most recent runs where it failed:
https://github.com/eclipse-bluechi/bluechi/actions/runs/8614446784

Since it seems to randomly fail, a more in-depth analysis is needed here.

## To Reproduce

Not sure yet. A more in-depth analysis why the test fails (seemingly randomly) is needed.

## Expected behavior

The test `proxy-service-propagate-target-service-failure` should always pass.

**Comment by ArtiomDivak** [comment]
Please assign me to this issue

**Comment by engelmi** [comment]
Fixed in #943. Closing.
