### ISSUE TITLE
Move man pages for SELinux policy

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#875]
## Please describe what information you were trying to find

Currently, the man pages for the SELinux policy of BlueChi are located in the selinux directory and in roff format:
https://github.com/eclipse-bluechi/bluechi/blob/main/selinux/bluechi_agent_selinux.8
https://github.com/eclipse-bluechi/bluechi/blob/main/selinux/bluechi_controller_selinux.8

They should be in markdown format and be displayed on the readthedocs as well:
- [x] Transform selinux policy man pages to markdown format
- [x] Move selinux policy man pages (in md) to others in https://github.com/eclipse-bluechi/bluechi/tree/main/doc/man
- [x] Add a new page for both policies in https://github.com/eclipse-bluechi/bluechi/tree/main/doc/docs/man and add them as list items under a new `SELinux` section here: https://github.com/eclipse-bluechi/bluechi/blob/main/doc/mkdocs.yml#L35-L43
- [x] Add a new `man8` list (similar to [man5](https://github.com/eclipse-bluechi/bluechi/blob/main/doc/man/meson.build#L20-L23)) listing both selinux man pages and add it to the list of pairs: https://github.com/eclipse-bluechi/bluechi/blob/main/doc/man/meson.build#L26

**Comment by schastlivcev** [comment]
Hi, I'd like to try to implement this)

**Comment by engelmi** [comment]
Hi @schastlivcev, cool! Looking forward to your contribution :) 
I'll assign this issue to you then. If you have any question, don't hesitate to ask.

**Comment by engelmi** [comment]
@schastlivcev And as a heads-up before submitting the PR:
Bluechi is a part of the Eclipse Foundation, and according to the contribution guidelines in order to contribute to the project you need to sign the Eclipse Contributor Agreement: https://www.eclipse.org/legal/ECA.php
Could you create an Eclipse account and sign ECA?

**Comment by schastlivcev** [comment]
I signed ECA and created PR
