### ISSUE TITLE
Failing Integration Tests in multihost mode

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#879]
## Describe the bug

https://github.com/eclipse-bluechi/bluechi/pull/878 added the (manually triggered) Workflow for running BlueChi's integration tests in multihost mode on testing farm. When running those on `Fedora-rawhide`, a bunch of tests are failing due to Timeout (as far as I've seen during a quick check), see for example:
Triggered GitHub Action: https://github.com/eclipse-bluechi/bluechi/actions/runs/8705253129/job/23875254490
Testing Farm Run: http://artifacts.osci.redhat.com/testing-farm/da6aff4d-e39b-4696-a1f9-3658cd961afd/

We need to investigate the root cause. This most likely doesn't affect anything in BlueChi itself, but only the integration tests (e.g. stability of checking conditions, etc.).  

## To Reproduce

Trigger the integration tests to run on testing farm in multihost mode for `Fedora-Rawhide` (e.g. via GH Workflow).

**Comment by dracher** [comment]
i will take this issue

**Comment by engelmi** [comment]
After investigation, it seems the test failures are related to the latest change in the SELinux policy (#850). 
This will be tackled in #883. Therefore closing this issue in favor of #883 and #884.
