### ISSUE TITLE
RFE: Add ListUnitFiles API

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#889]
## Please describe what you would like to see

This RFE resulted from https://github.com/eclipse-bluechi/bluechi/issues/887.

Based on how [systemctl list-units](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#list-units%20PATTERN%E2%80%A6) works, it is not possible to query services that aren't reference in any way (e.g. via `RequiredBy = multi-user.target`) or are active/failed.
systemd's [ListUnitFiles API](https://www.freedesktop.org/wiki/Software/systemd/dbus/) can be used to address this issue and return a list of **files**. So in order to enable a more complete view of available services, a new API for listing unit files should be added to BlueChi. 

## Please describe the solution you'd like

- [x] `bluechi-controller`: Add new API method on public DBus and delegate to `bluechi-agent`
- [x] `bluechi-agent`: Add new API on internal DBus and delegate to systemd bus
- [x] `bluechictl`: Add new command `list-unit-files [file-name-pattern]` where pattern can be used to filter by file name glob (similar to bluechictls [list-units](https://github.com/eclipse-bluechi/bluechi/blob/main/src/client/method-list-units.c#L202-L206))
- [x] Implement integration tests
- [x] Extend documentation (man pages, examples, etc.)
- [x] Refactor `ListUnitsRequest` and `ListUnitFilesRequest` by unifying these structs and the respective functions (see [this comment](https://github.com/eclipse-bluechi/bluechi/pull/915#discussion_r1692633935)) (https://github.com/eclipse-bluechi/bluechi/pull/923)

## Please describe your use case

For example, systemd services generated from quadlet files are not visible via `ListUnits` method (based on how [systemctl list-units](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#list-units%20PATTERN%E2%80%A6) works). Using [list-unit-files](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#list-unit-files%20PATTERN%E2%80%A6) such service files can be queried as well.

**Comment by trev-allison03** [comment]
Assign to me
