### ISSUE TITLE
Node: use configuration file on start

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#9]
## Please describe what you would like to see

When starting a node, it should read and use the configuration file to bootstrap itself.

## Please describe the solution you'd like

The configuration for the orchestrator could look like

```ini
[Configuration]
OrchestratorIP=<ip>       # required
OrchestratorPort=<port>   # required
```

The path to the file should be passed via cli option, e.g. `node -c /path/to/file`.

**Comment by sdunnagan** [comment]
@engelmi This issue can be closed, since we have:
```hirte-agent -c $HIRTE_TOP/hirte/doc/example-hirte-agent.ini'```

**Comment by engelmi** [comment]
Has been done in #82. Closing.
