### ISSUE TITLE
linked centos-automotive-sig mailing list web page shows "This page either doesn't exist, or it moved somewhere else."

### ISSUE THREAD

**Issue by eriksjolund** [engelmi/hirte#909]
## Describe the bug

The web page
https://github.com/eclipse-bluechi/bluechi/blob/main/CONTRIBUTING.md
contains the link
https://lists.centos.org/mailman/listinfo/centos-automotive-sig/

but that web page contains the text
```
This page either doesn't exist, or it moved somewhere else.
```

Curl can show the text on the command-line
```
$ curl -s https://lists.centos.org/mailman/listinfo/centos-automotive-sig/ | grep "This page either doesn't exist, or it moved somewhere else." 
    <div class="alert alert-danger">This page either doesn't exist, or it moved somewhere else.</div>
```

**Comment by mwperina** [comment]
Thanks for reporting, we missed that CentOS mailing lists switched from mailman to postorius, so mailing list URL changed.
