### ISSUE TITLE
RFE: Add ResetFailed and ResetFailedUnit API

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#932]
This RFE resulted from https://github.com/eclipse-bluechi/bluechi/issues/931.

## Please describe what you would like to see

In order to be able to reset the `failed` state of all or one unit, it is necessary to extend BlueChi by the `ResetFailed` and `ResetFailedUnit` API provided in the systemd Manager API (see the [freedesktop systemd documentation](https://www.freedesktop.org/wiki/Software/systemd/dbus/). 

## Please describe the solution you'd like

- [x] `bluechi-controller`: Add new API method on public DBus for interface `org.eclipse.bluechi.Node` and delegate to `bluechi-agent`
   - [x]  `ResetFailed`
   - [x]  `ResetFailedUnit`
- [x] `bluechi-agent`: Add new API on internal DBus and delegate to systemd bus
   - [x]  `ResetFailed`
   - [x]  `ResetFailedUnit`
- [x] `bluechictl`: Add new commands for using the new API(s)
   - [x] `bluechictl reset-failed` should call `ResetFailed` to reset all failed units
   - [x] `bluechictl reset-failed <unit>` should call `ResetFailedUnit` to reset the failed status for the specified units. 
- [x] Implement integration tests
- [x] Extend documentation (man pages, examples, etc.)
   https://github.com/eclipse-bluechi/bluechi/pull/937

**Comment by ArtiomDivak** [comment]
Please assign this issue to my

**Comment by engelmi** [comment]
Done in https://github.com/eclipse-bluechi/bluechi/pull/933 and https://github.com/eclipse-bluechi/bluechi/pull/937. 
Closing.
