### ISSUE TITLE
RFE: Add globbing to reset-failed

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#936]
This is a followup of #932 and resulted from https://github.com/eclipse-bluechi/bluechi/pull/933#pullrequestreview-2279205189

## Please describe what you would like to see

It would be great to support globs in the `bluechictl reset-failed` command for the node and unit name. This way, the following usage of bluechictl would be possible:

```bash
# call reset failed for all services on all nodes
bluechictl reset-failed \* \*

# call reset-failed for my.service on all worker nodes (e.g. worker-1, worker-2, etc.)
bluechictl reset-failed worker-\* my.service

# call reset-failed for all instances of the mytemplate template unit 
bluechictl reset-failed worker-1 mytemplate@\*.service
```

## Please describe the solution you'd like

For this, the `reset-failed` command needs to be extended to: 
- [ ] Check if the node and/or unit name is a glob (see [libbluechi/common/string-util.h#is_glob(..)](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/common/string-util.h#L58-L60))
- [ ] If node is a glob: Get the list of all nodes and filter based on glob matching (see [libbluechi/common/string-util.h#match_glob(...)](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/common/string-util.h#L62-L78))
- [ ] If unit is a glob: Get the list of all units and filter based on glob matching (see [libbluechi/common/string-util.h#match_glob(...)](https://github.com/eclipse-bluechi/bluechi/blob/main/src/libbluechi/common/string-util.h#L62-L78))

**Comment by ArtiomDivak** [comment]
Can you please assign this to me?

**Comment by ArtiomDivak** [comment]
After a long discussion This PR will be closed because
- its complicated semantics (e.g. multiple globs in unit list)
- there is (not yet) a use case for it
- it manipulates the state of the system and with a glob you don't know which units will be affected
