### ISSUE TITLE
Agent should try to reconnect when connection goes down

### ISSUE THREAD

**Issue by alexlarsson** [engelmi/hirte#94]
The agent should detect when the connection to the manager gets broken and do something about it. This could be either retry, with exponential backoff, or just exit with an error, or a combination of the two. Possibly this should be a configuration option.

**Comment by alexlarsson** [comment]
Related, we should similarly retry connect on startup if the manager is not yet up.

**Comment by sdunnagan** [comment]
Fixed with PR #167.
