### ISSUE TITLE
RFE: Add GetDefaultTarget and SetDefaultTarget API

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#944]
## Please describe what you would like to see

In order to be able to get and set the default target of the system to boot into, it is necessary to extend BlueChi with the `GetDefaultTarget` and `SetDefaultTarget` API provided by the systemd Manager API (see the [freedesktop systemd documentation](https://www.freedesktop.org/wiki/Software/systemd/dbus/)). 
For more information about the boot process, see [here](https://www.freedesktop.org/software/systemd/man/latest/bootup.html#System%20Manager%20Bootup).

## Please describe the solution you'd like

- [x] `bluechi-controller`: Add new API methods on public DBus for interface `org.eclipse.bluechi.Node` and delegate to `bluechi-agent`
   - [x] `GetDefaultTarget`
   - [x] `SetDefaultTarget`
- [x] `bluechi-agent`: Add new API methods on internal DBus and delegate to systemd bus
   - [x] `GetDefaultTarget`
   - [x] `SetDefaultTarget`
- [x] `bluechictl`: Add new commands in bluechictl:
   - [x] `bluechictl get-default [nodename]` 
   Similar to [systemctl get-default](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#get-default)). `[nodename]` is required for now. Maybe later this can be changed - if `[nodename]` is not provided, print all default targets for all nodes
   - [x] `bluechictl set-default [nodename] [target]`
   Similar to [systemctl set-default TARGET](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#set-default%20TARGET). 
   The `target` needs to be a `.target` unit, so there should be pre-validation in place checking that the unit ends with `.target`.
- [x] Implement integration tests
- [x] Extend documentation (man pages, examples, etc.)

**Comment by ArtiomDivak** [comment]
Please assign this to me

**Comment by mwperina** [comment]
Fixed by https://github.com/eclipse-bluechi/bluechi/pull/951
