### ISSUE TITLE
Use CLOCK_MONOTONIC for heartbeat feature

### ISSUE THREAD

**Issue by dofmind** [engelmi/hirte#952]
## Please describe what you would like to see

We get the current time using CLOCK_REALTIME. This reflects the current date and time, which can be adjusted by the system (e.g. NTP synchronization or manual change by the administrator). 

```
uint64_t get_time_micros() {
        struct timespec now;                                                                                           
        if (clock_gettime(CLOCK_REALTIME, &now) < 0) {                                                                 
                return 0;                                                                                              
        }                                                                                                              
        uint64_t now_micros = now.tv_sec * sec_to_microsec_multiplier +                                                
                        (uint64_t) ((double) now.tv_nsec * nanosec_to_microsec_multiplier);                            
        return now_micros;                                                                                             
}
```

We use the heartbeat signal to compare the current timestamp with the last seen timestamp of the opposite node to determine if the connection is lost. However, if the system time is suddenly jumped by NTP or the administrator, the difference between the current timestamp and the last seen timestamp may be greater than a threshold even if the connection is not lost.

This can be avoided by using CLOCK_MONOTONIC instead of CLOCK_REALTIME.

**Comment by mkemel** [comment]
Good idea!

Looking at the properties systemd provides for, say, Unit interface - you can see that each timestamp is provided in two forms - regular and monotonic, e.g.:
```
StateChangeTimestamp=Mon 2024-10-07 16:54:32 IDT
StateChangeTimestampMonotonic=1203399383937
InactiveExitTimestamp=Mon 2024-10-07 16:54:32 IDT
InactiveExitTimestampMonotonic=1203399223551
ActiveEnterTimestamp=Mon 2024-10-07 16:54:32 IDT
ActiveEnterTimestampMonotonic=1203399383937
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
```
I think we should do the same for the timestamps we provide - to give the user tools to both see the real time and to measure elapsed time in a reliable way.
