### ISSUE TITLE
Remove specific tests timeouts and rely on the whole test timeout

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#973]
As a part of https://github.com/eclipse-bluechi/bluechi/issues/969 we made timeouts used in testing infrastructure configurable. Unfortunately we have also following tests, which uses their own timeout values, which also need to be configurable for those tests to pass on slower hardware platforms:

- https://github.com/eclipse-bluechi/bluechi/blob/main/tests/tests/tier0/bluechi-change-port-with-c-cmd-option/test_bluechi_change_port_with_c_cmd_option.py#L33
- https://github.com/eclipse-bluechi/bluechi/blob/main/tests/tests/tier0/bluechi-change-port-with-p-cmd-option/test_bluechi_change_port_with_p_cmd_option.py#L32
- https://github.com/eclipse-bluechi/bluechi/blob/main/tests/tests/tier0/bluechi-agent-user-bus/python/start_agent_as_user.py#L22

For now it might be enough to introduce new timeout value used inside all above tests and make it configurable the same way as in https://github.com/eclipse-bluechi/bluechi/issues/969.
Or remove those specific timeouts from tests completely and rely only on the whole test timeout ...

**Comment by engelmi** [comment]
We don't handle these timeouts and the log messages aren't that helpful for debugging (we should get the same information from the stacktrace). So I think removing those timeouts would be best. The timeouts for setup, execution and artifact collection would be still in place and prevent any test from hanging.
