### ISSUE TITLE
Add integration tests for bluechi-is-online agent without any cli options

### ISSUE THREAD

**Issue by engelmi** [engelmi/hirte#981]
## Please describe what you would like to see

In https://github.com/eclipse-bluechi/bluechi/issues/962 the new package bluechi-is-online was introduced. However, adding integration tests was postponed. 

A basic integration test for `bluechi-is-online agent` would verify that:
- it exists with code 1 when the `bluechi-agent` is not connected
- it exits with code 0 when the `bluechi-agent` is connected

<br>
<br>

**Tech hints**
- `bluechi-is-online` needs to run on the agent node
- `bluechi-is-online` can be wrapped in a systemd unit and check the unit state inactive/failed (see [the docs](https://bluechi.readthedocs.io/en/latest/tools/bluechi-is-online/#usage-example))

**Comment by DanaOrr** [comment]
Please assign this ticket to me
